### ISSUE TITLE
`--version=latest` rejected as invalid

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium-cli#1006]
```
$ ./cilium install --agent-image=quay.io/cilium/cilium-ci --operator-image=quay.io/cilium/operator-generic-ci --version=latest
Invalid character(s) found in major number "0latest"
```
This used to work but seems broken at least on the latest, unreleased version.

**Comment by tklauser** [comment]
FWIW, adding a valid `--chart-directory` to the command should work. But obviously we should make that clearer in the error message.

**Comment by pchaigno** [comment]
> FWIW, adding a valid --chart-directory to the command should work.

I can confirm that works.
