### ISSUE TITLE
Inconsistency in clustermesh setup between Helm and Cilium CLI installations

### ISSUE THREAD

**Issue by carnerito** [cilium/cilium-cli#1053]
## Bug report

Cilium `clustermesh status` command not working when clustermesh is installed using Helm. I found 2 issues that are causing this issue.

#### 1. Client secret name
Cilium CLI and Helm are naming clustermesh secrets differently. This causes Cilium CLI `clustermesh status` command to fail if Cilium clustermesh is installed using Helm. The difference is in trailing 's' in secret names that Cilium CLI appends to clustermesh secrets. 
Secrets that have different names in Helm templates and Cilium CLI are:
- clustermesh-apiserver-server-cert
- clustermesh-apiserver-admin-cert
- clustermesh-apiserver-client-cert
- clustermesh-apiserver-external-workload-cert

If Cilium clustermesh is enabled using `clustermesh.config` Helm values, if I try to check clustermesh status using Cilium CLI command, I'm getting the following error:
```Error: Unable to determine status:  unable to get secret "clustermesh-apiserver-client-certs" to access clustermesh service: secrets "clustermesh-apiserver-client-certs" not found```

If I recreate the client cert secret created by Helm to `clustermesh-apiserver-client-certs` which Cilium CLI expects, the `clustermesh status` command terminates with another error.  This error is described below.

#### 2. External workload secret
Cilium CLI `clustermesh enable` command creates a secret for the external workload (`installCertificates` method in clustermesh/certs.go). Helm doesn't generate this secret which is causing  this error:
```Error: Unable to determine status:  unable to get secret "clustermesh-apiserver-client-certs" to access clustermesh service: secrets "clustermesh-apiserver-external-workload-certs" not found```
This secret is not used in `clustermesh status` and I think that it shouldn't be checked for this command.

**General Information**

- Cilium CLI version
`cilium-cli: v0.12.1 compiled with go1.18.5 on darwin/arm64
cilium image (default): v1.12.0
cilium image (stable): v1.12.1
cilium image (running): v1.12.0`

- Orchestration system version in use
`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:47:37Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}`

- Helm Chart version
`1.12.0`

**How to reproduce the issue**

1. Configure clustermesh values in Helm values file:
- clustermesh.useAPIServer: true
- clustermesh.config.enabled: true
- clustermesh.config.clusters: _clusters configuration_
2. Install Cilium 
`helm install cilium cilium/cilium --version 1.12.0 --namespace kube-system --values values.yml`
3. Wait for clustermesh to start 
4. Run `cilium clustermesh status` command

**Comment by georgew5656** [comment]
I believe there is still a issue separate from the naming here, the helm chart doesn't create the clustermesh-apiserver-client-cert unless externalWorkloads is enabled, but the clustermesh setup assumes that the secret will exist even though its not used unless there are external workloads.
