### ISSUE TITLE
bug: cilium sysdump predates global `--namespace` flag

### ISSUE THREAD

**Issue by ernado** [cilium/cilium-cli#1079]
That is, currently you should do:
```console
cilium sysdump --cilium-namespace=cni
```
But this probably should also work (but it fails, defaulting to `kube-system`):
```console
cilium --namespace=cni sysdump
```

**Comment by ChrsMark** [comment]
@tklauser @qmonnet I have pushed a patch for this in https://github.com/cilium/cilium-cli/pull/1302. Raising this here too for awareness :).
