### ISSUE TITLE
How should we update the cilium-agent version used by the CLI?

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium-cli#118]
Users are likely to pull the cilium-cli binary once and not update it particularly frequently.

Currently, we are embedding the "latest" version of the main Cilium components into the binary directly:

https://github.com/cilium/cilium-cli/blob/3e55a2a9c006312e63df41c4eb41baeb63a86ccc/defaults/defaults.go#L79

This means that the version will get out-of-date very easily, and even if we create a new cilium/cilium-cli release every time we do a stable branch release on cilium/cilium, if users do not update their CLI then by default they will get an older release. This is likely to include more bugs and potentially unresolved security issues.

How should we best handle pulling the latest stable release as part of `cilium install`?

**Comment by tgraf** [comment]
I was considering pulling it automatically from GitHub or an API. Thoughts?

**Comment by rolinh** [comment]
I think pulling from Github makes sense. For the Hubble CLI, we have a [`stable.txt` file at the root](https://github.com/cilium/hubble/blob/master/stable.txt) that contains the version of the latest stable Hubble CLI release. It's used in the doc so that we always instruct to download the latest CLI version without having to bump it in the docs.

**Comment by nbusseneau** [comment]
We now also have [`stable.txt`](https://github.com/cilium/cilium/blob/cee08cd2b29927f81e2eca3ad4aea8741a380d70/stable.txt) on `cilium/cilium`, see #272 for context. Note that the 2 issues are still independent: #272 assumes we keep going with the current workflow, which is pinning each CLI release to a Cilium version.

On the other hand: #273 is related, and proposes an alternative by keeping versions pinned but notifying users of new CLI updates.
