### ISSUE TITLE
Specifying cilium version to install with `cilium install --version` fails

### ISSUE THREAD

**Issue by etungsten** [cilium/cilium-cli#1189]
## Bug report

**General Information**
Specifying the cilium version when installing with cilium CLI fails:
Without 'v':
```bash
$ cilium install --version 1.21.2
chart "cilium" version "1.21.2" not found in https://helm.cilium.io repository
```
With 'v':
```bash
$ cilium install --version v1.21.2
chart "cilium" version "1.21.2" not found in https://helm.cilium.io repository
```

Usage info for `--version` says
```
      --version string                       Cilium version to install (default "v1.12.2")
```
So I expected v1.12.2 to work.

- Cilium CLI version (run `cilium version`)
```bash
$ cilium version
cilium-cli: v0.12.4 compiled with go1.19.1 on linux/amd64
cilium image (default): v1.12.2
cilium image (stable): v1.12.3
```
- Orchestration system version in use (e.g. `kubectl version`, ...)
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-fb459a0", GitCommit:"b07006b2e59857b13fe5057a956e86225f0e82b7", GitTreeState:"clean", BuildDate:"2022-10-24T20:32:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Platform / infrastructure information (e.g. AWS / Azure / GCP, image / kernel versions)
EKS
- Link to relevant artifacts (policies, deployments scripts, ...)
N/A
- Generate and upload a system zip: `cilium sysdump`
N/A
**How to reproduce the issue**

1. `cilium install --version <any cilium version>`

**Comment by aanm** [comment]
Hi @etungsten, thanks for the bug report but we haven't released Cilium `1.21.2` so that error is expected.

**Comment by etungsten** [comment]
Ah, I see. It worked with `1.21.3`. I only tried `1.21.1` and `1.21.2`. I think the usage info is still misleading though. Thanks!

**Comment by aanm** [comment]
@etungsten it does work for me. Except anything above 1.12.4 since we haven't released anything above that version.
```
$ cilium install --version 1.12.2
🔮 Auto-detected Kubernetes kind: minikube
✨ Running "minikube" validation checks
✅ Detected minikube version "1.27.1"
...

$ cilium install --version 1.12.3
🔮 Auto-detected Kubernetes kind: minikube
✨ Running "minikube" validation checks
✅ Detected minikube version "1.27.1"
...
$ cilium install --version 1.12.4
chart "cilium" version "1.12.4" not found in https://helm.cilium.io repository
```
