### ISSUE TITLE
Clilium-cli generates wrong helm command

### ISSUE THREAD

**Issue by g00ntar** [cilium/cilium-cli#1205]
## Bug report

**General Information**

- Cilium CLI version 0.12.6 (0.12.0 too)
- Orchestration system version in use v1.25.3+k3s
- Ubuntu 20.04 amd64 / Alpine 3.16 aarch64

**How to reproduce the issue**

1. install k3s via 
```
curl -sfL https://get.k3s.io | sh -s server \
--write-kubeconfig-mode 644 --flannel-backend=none \
--disable-network-policy --disable-kube-proxy \
--disable-cloud-controller --disable servicelb
```
2. try install cilium via cli
```
cilium install --config tunnel=disable \
--config install-no-conntrack-iptables-rules=true
```

**Expected outcome**
Cilium insatelld properly

**Actual outcome**
```
🔮 Auto-detected Kubernetes kind: K3s
ℹ️  Using Cilium version 1.12.2
🔮 Auto-detected cluster name: default
🔮 Auto-detected datapath mode: tunnel
🔮 Auto-detected kube-proxy has not been installed
ℹ️ Cilium will fully replace all functionalities of kube-proxy
⚠️ Unable to list kubernetes api resources, try --api-versions if needed: %!w(*fmt.wrapError=&{failed to list api resources: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request 0x400000e320})
ℹ️  helm template --namespace kube-system cilium cilium/cilium --version 1.12.2 --set cluster.id=0,cluster.name=default,encryption.nodeEncryption=false,extraConfig.install-no-conntrack-iptables-rules=true,extraConfig.tunnel=disable,k8sServiceHost=127.0.0.1,k8sServicePort=6443,kubeProxyReplacement=strict,operator.replicas=1,serviceAccounts.cilium.name=cilium,serviceAccounts.operator.name=cilium-operator,tunnel=vxlan
ℹ️  Storing helm values file in kube-system/cilium-cli-helm-values Secret
🔑 Created CA in secret cilium-ca
🔑 Generating certificates for Hubble...
🚀 Creating Service accounts...
🚀 Creating Cluster roles...
🚀 Creating ConfigMap for Cilium version 1.12.2...
ℹ️ Manual overwrite in ConfigMap: tunnel=disable
ℹ️ Manual overwrite in ConfigMap: install-no-conntrack-iptables-rules=true
↩️ Rolling back installation...

Error: Unable to install Cilium: cannot generate ConfigMap: --install-no-conntrack-iptables-rules requires tunneling to be disabled
```

As we see we get `helm template --namespace kube-system cilium cilium/cilium --version 1.12.2 --set cluster.id=0,cluster.name=default,encryption.nodeEncryption=false,extraConfig.install-no-conntrack-iptables-rules=true,extraConfig.tunnel=disable,k8sServiceHost=127.0.0.1,k8sServicePort=6443,kubeProxyReplacement=strict,operator.replicas=1,serviceAccounts.cilium.name=cilium,serviceAccounts.operator.name=cilium-operator,tunnel=vxlan` with `tunnel=vxlan` instead of `tunnel=disabled`

**Comment by Shunpoco** [comment]
I found that your miswrote the option. Please use `--config tunnel=disabled` (now you use `disable`)
I think then you would have the following error:
```console
Error: Unable to install Cilium: cannot generate ConfigMap: --install-no-conntrack-iptables-rules requires kube-proxy replacement to be enabled
```
In order to enable `install-no-conntrack-iptables-rules`, we have to add
- `tunnel=disabled`
- `kube-proxy-replacement=strict`
- `enable-bpf-masquarade=true`
- `cni-chaining-mode=""`


Please see this part of code: https://github.com/cilium/cilium-cli/blob/master/install/install.go#L444-L458

**Comment by xiaods** [comment]
this is typo, not issue
