### ISSUE TITLE
Cilium-cli don't behave as described in docs

### ISSUE THREAD

**Issue by g00ntar** [cilium/cilium-cli#1206]
## Bug report

**General Information**

- Cilium CLI version 0.12.6/0.12.0
- Ubuntu 20.04 amd64 / Alpine 3.16 aarch64
 
**How to reproduce the issue**

1. run `cilium config --list-options` as described [here](https://docs.cilium.io/en/v1.12/cmdref/cilium_config/)

**Expected outcome**
Output with list of applicable options

**Actual outcome**
`unknown flag: --list-options`

**Comment by tklauser** [comment]
The referenced documentation is referring to the per-pod binary which unfortunately is also named `cilium`. If you want to run that command you could use something like `kubectl exec -it ds/cilium cilium config --list-options`.
