### ISSUE TITLE
Display help message if `cilium` per-cluster command is invoked with sub-command for per-node `cilium` command

### ISSUE THREAD

**Issue by tklauser** [cilium/cilium-cli#1229]
Unfortunately, both the per-cluster CLI (i.e. the CLI maintained in this repository) and the per-node CLI (maintained in the `cilium/cilium` repo at https://github.com/cilium/cilium/tree/master/cilium) are named `cilium` which leads to confusion from time to time, see e.g. https://github.com/cilium/cilium-cli/issues/1206.

@aanm suggested to add a help message to the per-cluster `cilium` command which is displayed in case they are invoked with a sub-command only supported by the per-node `cilium` command:

> ... add a message, in addition to the helper message, asking if the user wanted to try out the cilium cli inside the container and giving a command example on how to do it

Additionally we could/should also update the Cilium docs to clarify the difference between the two commands.

**Comment by aanm** [comment]
@kranurag7 any update?

**Comment by tklauser** [comment]
The in-container CLI was renamed to `cilium-dbg` by https://github.com/cilium/cilium/pull/28085 which should help avoid the confusion, thus closing this for now.
