### ISSUE TITLE
ClusterMesh With ClusterIP service type

### ISSUE THREAD

**Issue by SebastienTolron** [cilium/cilium-cli#1247]
Hello ,

This is more a question than a bug or a feature request.

I'm trying to setup clusterMesh using ClusterIP service type.

My Api cluster mesh has an internal IP then :  100.80.34.67. I am on cluster A

My Other cluster ( Cluster B ) of course can't contact this IP because its an internal ip for the Cluster A. So of course they can't talk to each other.

Am I missing anything here ? Is it my responsabilitie to make change in IP table so they can communicate each other with this internal IP ? Is cilium supposed to manage that ?  

It is not very clear in the documentation.

Thanks in advance !

Regards

P.S : I know I could use MetalLB with a LoadBalancer  service type and  make it works but I want to know about ClusterIP.

**General Information**

- Cilium CLI version (run `cilium version`)
```
cilium-cli: v0.12.7 compiled with go1.19.3 on linux/amd64
cilium image (default): v1.12.2
cilium image (stable): v1.12.4
cilium image (running): v1.12.4
```

- Orchestration system version in use (e.g. `kubectl version`, ...)
```
v1.25.4
```

- Platform / infrastructure information (e.g. AWS / Azure / GCP, image / kernel versions)

```
On Premise 
VmWare for VM
Debian GNU/Linux 11 (bullseye)    /   Kernel 5.10.0-14-amd64 
cri-o://1.25.1
```

**Comment by giorio94** [comment]
Using a ClusterIP service to expose the clustermesh-apiserver is hardly ever working, as this component must be reachable from other clusters. I've recently opened https://github.com/cilium/cilium-cli/pull/2664 to remove this possibility from the help message, and trigger an error in case it is configured.
