### ISSUE TITLE
Allow to install Hubble in one command

### ISSUE THREAD

**Issue by raphink** [cilium/cilium-cli#1309]
## Proposal / RFE

At the moment, enabling Hubble is done is two steps.

It would be useful to have `--enable-hubble` and `--enable-hubble-ui` flags directly in the `cilium install` command, so it can all be installed in one command.

**Comment by bimmlerd** [comment]
I think this is a duplicate of https://github.com/cilium/cilium-cli/issues/425

**Comment by tklauser** [comment]
Duplicate of #425
