### ISSUE TITLE
Show version of cilium (as well as of cilium-cli) 

### ISSUE THREAD

**Issue by lizrice** [cilium/cilium-cli#131]
`cilium version` reports the version of the CLI agent. It would be useful if it also showed the running version of cilium (there's already a [TODO comment](https://github.com/cilium/cilium-cli/blob/f05d883cedea527377fac6a23a6849ba39b2a8ea/internal/cli/cmd/version.go#L47) to this effect)

**Comment by rolinh** [comment]
See also related discussion on PR #121.
