### ISSUE TITLE
Cancelling failing cilium-health probes results in a tight loop which spams the terminal.

### ISSUE THREAD

**Issue by bimmlerd** [cilium/cilium-cli#1314]
## Bug report

Persistenly failing cilium-health probes are in a loop until some general timeout: https://github.com/cilium/cilium-cli/blob/30310b18ae7751beb43744691c2e68c589b65861/connectivity/tests/health.go#L43-L65

Typical log would be
```
⚠️  cilium-health validation failed: "cilium-agent 'kube-system/cilium-wgcls': connectivity to path 'kind-worker.health-endpoint.primary-address.http.status' is unhealthy: 'Get \"http://10.0.0.12:4240/hello\": read tcp 10.0.1.135:50650->10.0.0.12:4240: read: connection reset by peer'", retrying...
```

As a result, one might want to stop the health check prematurely, e.g. with a Ctrl+C. This seems to cancel `ctx`, upon which https://github.com/cilium/cilium-cli/blob/30310b18ae7751beb43744691c2e68c589b65861/connectivity/tests/health.go#L46-L50 fails with 

```
  cilium-health probe failed: "error sending request: Post \"https://127.0.0.1:53497/api/v1/namespaces/kube-system/pods/cilium-wgcls/exec?command=cilium-health&command=status&command=--probe&command=-o%3Djson&stderr=true&stdout=true\": dial tcp 127.0.0.1:53497: operation was canceled", stdout: {"" '\x00' '\x00'}, retrying...
```

Because of the `continue`, this just leads to a tight loop, spamming the above warning into the terminal at a high rate.

**General Information**

- Cilium CLI version (run `cilium version`)
```
cilium-cli: v0.12.11-40-g2fc0835f compiled with go1.19.4 on darwin/arm64
cilium image (default): v1.12.4
cilium image (stable): v1.12.5
cilium image (running): v1.12.5
```
- Orchestration system version in use (e.g. `kubectl version`, ...)
```
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.25.3
```
- Platform / infrastructure information: Kind

**How to reproduce the issue**

~I'm not sure why the health probes ended up failing in the first place, but once in that state, it's easy 😅~

1. Start kind _without_ specifying `disableDefaultCNI: true`, but with multiple nodes. The following works with `kind create cluster --config ...`:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
```
2. Run `cilium connectivity test --test health`. You should see failing health probes now, with the above log.
3. Press Ctrl+C
4. See spam fly by on the console.

**Comment by tklauser** [comment]
I agree this should be fixed. It seems like we should check `ctx.Done()` if `pod.K8sClient.ExecInPod` returns an error and only continue if the context wasn't cancelled (or the timer expired, for that matter).

The fix should be fairly straight-forward, I'll mark this as `good-first-issue`.

**Comment by dharmicksai** [comment]
Hello 👋,
 i am interested in contributing to this issue 
/assign
