### ISSUE TITLE
Pod-to-host ICMP tests fail if NET_RAW capability is not provided by runtime

### ISSUE THREAD

**Issue by eyanulis** [cilium/cilium-cli#133]
On a 1.20.4 cluster deployed with CRI-O 1.20.0 and "v6-first" dual-stack, I observe the following failures in the pod-to-host tests (IPs have been altered):

```
---------------------------------------------------------------------------------------------------------------------
🔌 [pod-to-host] Testing cilium-test/client-58dfdc5f6-fkgxg -> 2001:db8:0:1::21...
---------------------------------------------------------------------------------------------------------------------
❌ ping command failed: error in stream: command terminated with exit code 1
❌ [pod-to-host] cilium-test/client-58dfdc5f6-fkgxg (2001:db8:0:0:3::1234) -> 2001:db8:0:1::21 (2001:db8:0:1::21)
```

Exec'ing into the pod shows the failure is caused by insufficient permissions:

```
/ # ping 2001:db8:0:1::21
PING 2001:db8:0:1::21 (2001:db8:0:1::21): 56 data bytes
ping: permission denied (are you root?)
/ # echo $?
1
```

This appears to stem from the pod lacking the `NET_RAW` capability. In my specific case, this happens because CRI-O above 1.18.0 no longer gives `NET_RAW` to containers by default, as implemented in https://github.com/cri-o/cri-o/pull/3119.

However, I assume this would also bite folks who are deploying their clusters with non-CRI-O runtimes but with restrictive pod security contexts lacking `NET_RAW`.

CRI-O offers a few ways to allow ping (enabling `NET_RAW`, enabling the `ip_forward` sysctl, etc) but I'm unsure of the best way to fix this in the more generic context of the Cilium CLI in "all possible container runtimes" (or if it's something that even _should_ be considered here).

Figured it was probably worth opening an issue to discuss before flinging code at the problem.

**Comment by Jean-Daniel** [comment]
Same issue here (CRI-O too).

I guess the simplest solution would simply to patch the security context of the containers that needs to ping to include NET_RAW.

```yaml
    securityContext:
      capabilities:
        add:
          - NET_RAW
```

**Comment by asteven** [comment]
With the patch from #271 all tests run to completion against a crio 1.21.0 with default config.

```
cilium-cli% ./cilium connectivity test -n cilium
ℹ️  Single-node environment detected, enabling single-node connectivity test
ℹ️  Monitor aggregation detected, will skip some flow validation steps
...
 All 9 tests (55 actions) successful, 0 warnings, 0 tests skipped, 0 scenarios skipped.
Interrupt received, cancelling tests...
cilium-cli%
```
