### ISSUE TITLE
Cilium CLI generates Hubble server certificate with wrong common name when cluster name is provided from Helm values

### ISSUE THREAD

**Issue by YutaroHayakawa** [cilium/cilium-cli#1347]
## Bug report

`cilium install` sets `k.params.ClusterName` with auto-detected value when `--cluster-name` is not specified.

https://github.com/cilium/cilium-cli/blob/d459a7c95c210debab7514dfd3beb5f1197343ca/install/autodetect.go#L134-L140

When the cluster name is provided through Helm values (`--helm-set` or `--helm-values`), the one user-specified will be used because Helm values always take precedence over auto-detected values.

https://github.com/cilium/cilium-cli/blob/d459a7c95c210debab7514dfd3beb5f1197343ca/internal/helm/helm.go#L340-L341

However, after generating the Helm manifests, Cilium CLI uses `k.params.ClusterName` to set the common name of the Hubble server certificate in installCerts -> createHubbleServerCertificate.

https://github.com/cilium/cilium-cli/blob/d459a7c95c210debab7514dfd3beb5f1197343ca/install/certs.go#L22

As a result, when the cluster name provided by Helm values and auto-detected values are different, `hubble-relay` fails to connect to `hubble-peer`, because Hubble-relay uses the cluster name from Helm value and builds the wrong server name, which doesn't match the name in the server certificate and fails to connect to hubble-peer service.

https://github.com/cilium/cilium/blob/6b58ed54735dbc460700f922f8ce91cf3059a25a/pkg/hubble/relay/server/server.go#L80-L85

```
level=warning msg="Failed to create peer client for peers synchronization; will try again after the timeout has expired" error="context deadline exceeded" subsys=hubble-relay target="hubble-peer.kube-system.svc.cluster.local:443"
level=warning msg="Failed to create peer client for peers synchronization; will try again after the timeout has expired" error="context deadline exceeded" subsys=hubble-relay target="hubble-peer.kube-system.svc.cluster.local:443"
```

I think some users in this issue (https://github.com/cilium/cilium/issues/20130) were affected by this.

In my case, I created the Kind cluster with the name `cluster1` and cluster name auto-detection detects the name `kind-cluster1`, which comes from the name of the kubeconfig context generated by Kind (this could be another problem, maybe the auto-detected name should be `cluster1`?).

The thing that makes this problem complicated is when we specify `--cluster-name`, Cilium CLI encourages us to fix it to `helm-set`, but changing `--cluster-name` to `--helm-set cluster.name=<clusterName>` causes the above issue.

```
Flag --cluster-name has been deprecated, This can now be overridden via `helm-set` (Helm value: `cluster.name`).
```

**Comment by michi-covalent** [comment]
@YutaroHayakawa this should no longer be an issue since we have removed support for classic mode installations. could you test this again when you get a chance? 🚀🙏

**Comment by michi-covalent** [comment]
alright i'm closing this. please re-open if you hit the issue again 🙏
