### ISSUE TITLE
Seamless Cilium CLI + Helm

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium-cli#1396]
Allow Cilium CLI to work seamlessly with Helm by using Helm as the backend for installation.

There are a number of issues opened already which reference this, but no one issue to describe the entirety of the problem. This is an umbrella issue for

* https://github.com/cilium/cilium-cli/issues/515
* https://github.com/cilium/cilium-cli/issues/751
* https://github.com/cilium/cilium-cli/issues/1106

**Comment by giorio94** [comment]
Related: https://github.com/cilium/cilium-cli/issues/1391

**Comment by lambdanis** [comment]
Another issue that would benefit from this: #1422

Also, there were problems when creating 3rd party custom resources (e.g. #1107) as `helm template` commands run by Cilium CLI don't interact with k8s API. A proper Helm integration would solve it too.

**Comment by xiaods** [comment]
any update on it?

**Comment by lambdanis** [comment]
@xiaods Yes. The README documents the [helm installation mode](https://github.com/cilium/cilium-cli/tree/v0.15.8#helm-installation-mode), introduced in v0.14 and used by default since v0.15.

**Comment by christarazi** [comment]
@xiaods With the latest CLI, does it resolve your problems?

**Comment by xiaods** [comment]
> @xiaods With the latest CLI, does it resolve your problems?

not yet.

```
[root@ip-172-31-0-254 ~]# cilium version
cilium-cli: v0.15.7 compiled with go1.21.0 on linux/amd64
cilium image (default): v1.14.1
cilium image (stable): v1.14.2
cilium image (running): 1.14.1


[root@ip-172-31-0-254 ~]# cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    disabled (using embedded mode)
 \__/¯¯\__/    Hubble Relay:       disabled
    \__/       ClusterMesh:        disabled

DaemonSet              cilium             Desired: 1, Ready: 1/1, Available: 1/1
Deployment             cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Containers:            cilium             Running: 1
                       cilium-operator    Running: 1
Cluster Pods:          3/3 managed by Cilium
Helm chart version:    1.14.1
Image versions         cilium             quay.io/cilium/cilium:v1.14.1@sha256:edc1d05ea1365c4a8f6ac6982247d5c145181704894bb698619c3827b6963a72: 1
                       cilium-operator    quay.io/cilium/operator-generic:v1.14.1@sha256:e061de0a930534c7e3f8feda8330976367971238ccafff42659f104effd4b5f7: 1
```
My requirements is :
strip the quay.io/cilium/cilium image tag without digests. because I found in airgap isntall environments. import images tar will get differents digest of cilium image.

**Comment by xiaods** [comment]
> @xiaods With the latest CLI, does it resolve your problems?

my image digest's issue have been resolved.

**Comment by sayboras** [comment]
I noticed the same while doing backport, it seems like we can still go ahead with backport PRs as the note says that it will not cause any impact for helm.

**Comment by pentago** [comment]
FWIW, I think `cilium install/uninstall` functionality is a mistake and shouldn't exist in the first place. Having just a helm chart that does the installation on Kubernetes should be the only way to deploy Cilium while using a config file everywhere else. Having CLI install a helm chart is such a weird architectural decision IMHO.

**Comment by xiaods** [comment]
> FWIW, I think `cilium install/uninstall` functionality is a mistake and shouldn't exist in the first place. Having just a helm chart that does the installation on Kubernetes should be the only way to deploy Cilium while using a config file everywhere else. Having CLI install a helm chart is such a weird architectural decision IMHO.

any proposal on improve it

**Comment by xiaods** [comment]
> Chart

pr welcome

**Comment by pentago** [comment]
Really? You as a core maintainer say that?
