### ISSUE TITLE
RFE: Extend external workload install script to detect if wireguard encryption is enabled on cluster

### ISSUE THREAD

**Issue by jspaleta** [cilium/cilium-cli#1400]
## Proposal / RFE

**Is your feature request related to a problem?**
Using wireguard encryption with external workloads is possible, but it requires the cilium agents running on external workloads to be configured with additional options.
The additional options are ` --enable-l7-proxy=false --enable-wireguard=true`

**Describe the solution you'd like**
I would like the install script generator to be able to test to see if the current cilium cluster is using wireguard and if so add the additional options into the generated script via an additional `CILIUM_OPTS+` construction.

I've manually tested this using an external Azure VM and a cilium v1.12.5 managed AKS cluster, by adding the arguments myself after the install script was generated and confirmed that the external vm's cilium_wg0 interface traffic using tcpdump.

**Comment by tklauser** [comment]
> The additional options are ` --enable-l7-proxy=false --enable-wireguard=true`

Note that we won't need `--enable-l7-proxy=false` when installing Cilium v1.13.0 or later, see #1405. So setting that option should probably be made conditional on the Cilium version being installed.

**Comment by jspaleta** [comment]
> > The additional options are ` --enable-l7-proxy=false --enable-wireguard=true`
> 
> Note that we won't need `--enable-l7-proxy=false` when installing Cilium v1.13.0 or later, see #1405. 

Yeah looks like its 1.14.0 or later.  I tested locally with 1.13.0 and it was still required there. But yes definitely needs to be version conditional.

**Comment by Neilblaze** [comment]
@jspaleta I think we can close this issue for now. Thanks! :)

**Comment by jspaleta** [comment]
Does it auto detect that encryption needs to be enabled now?
