### ISSUE TITLE
install: Don't disable L7 proxy when installing with WireGuard enabled

### ISSUE THREAD

**Issue by brb** [cilium/cilium-cli#1405]
Since https://github.com/cilium/cilium/pull/19401 (to be released in v1.14) we no longer need to disabled the L7 proxy when WireGuard is enabled on the > v1.13 Cilium (the relevant log message `L7 proxy disabled due to Wireguard encryption`).

As a bonus, we can remove the `Wireguard does not support node encryption yet` warning too.

**Comment by Neilblaze** [comment]
@brb If this is up for grabs, I'd love to work on this. 😄

**Comment by brb** [comment]
@Neilblaze :+1:
