### ISSUE TITLE
connectivity: Report which IP families are tested

### ISSUE THREAD

**Issue by brb** [cilium/cilium-cli#1410]
We should improve the connectivity reporting saying which IP families (i.e., v4 or v6) are being tested. 

Also, each Action description could contain the family too. E.g., we could report `curl-v4-1`, `curl-v6-2`, etc.

**Comment by Neilblaze** [comment]
@brb If this is up for grabs, I'd love to work on this. 😄

**Comment by brb** [comment]
Hey @Neilblaze , sure, go for it! Thanks.
