### ISSUE TITLE
cilium upgrade unknown flag: --azure-resource-group

### ISSUE THREAD

**Issue by philwelz** [cilium/cilium-cli#1430]
## Bug report

If you have Cilium installed and run `cilium upgrade` in an Azure BYOCNI environment, Cilium successfully discovered that the Kubernetes Kind ist AKS `Auto-detected Kubernetes kind: AKS` but states `Azure resource group is required, please specify --azure-resource-group`. If you then run  `cilium upgrade --azure-resource-group rg-test` you get the errror message `unknown flag: --azure-resource-group`

**General Information**

- Cilium CLI version : 012.2 & 0.13.0
- Orchestration system version in use : 1.25.3
- Platform / infrastructure information: Azure 

**How to reproduce the issue**

1. `cilium install --azure-resource-group rg-test`
2.  update cilium-cli to 0.13.0
3.  `cilium upgrade`
4.  `cilium upgrade --azure-resource-group rg-test`

**Comment by StepanKuksenko** [comment]
for me install doesn't work neither 
```
cilium install --azure-resource-group my-group --dry-run
unknown flag: --azure-resource-group

cilium install --dry-run-helm-values
Error: Unable to install Cilium: missing Azure resource group name
```

**Comment by philwelz** [comment]
> for me install doesn't work either cilium cli v.1.15.2
> 
> ```
> cilium install --azure-resource-group my-group --dry-run
> unknown flag: --azure-resource-group
> 
> cilium install --dry-run
> Error: Unable to install Cilium: missing Azure resource group name
> ```
> 
> i managed to make it this way `cilium install --helm-set aksbyocni.enabled=true --helm-set azure.resourceGroup=my-group --dry-run`

With Cilium-CLI v0.15.2 you could use this now:

```
cilium install \
    --datapath-mode aks-byocni \
    --set azure.resourceGroup="RG" 
```
