### ISSUE TITLE
cilium install --version doesn't let you install snapshot versions.

### ISSUE THREAD

**Issue by jspaleta** [cilium/cilium-cli#1448]
## Bug report

`cilium install --list-versions` includes `v1.14.0-snapshot.0`

But `cilium install --version "v1.14.0-snapshot.0"` results in error
`invalid parameters: invalid syntax "v1.14.0-snapshot.0" for image tag`

Looks like the version argument linting is too restrictive to allow the new snapshot version concept.

**General Information**

- Cilium CLI version 
```
$ cilium version
cilium-cli: v0.13.1 compiled with go1.20 on linux/amd64
cilium image (default): v1.13.0
cilium image (stable): v1.13.0
cilium image (running): unknown. Unable to obtain cilium version, no cilium pods found in namespace "kube-system"
```
- Orchestration system version in use (e.g. `kubectl version`, ...)
```
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

```
- Platform / infrastructure information (e.g. AWS / Azure / GCP, image / kernel versions)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip: `cilium sysdump`

**How to reproduce the issue**

1. Attempt to install any snapshot version listed in the output of `cilium install --list-versions`

**Comment by tklauser** [comment]
Thanks for the report @jspaleta. I can confirm the issue and I'm working on a fix.
