### ISSUE TITLE
CiliumEndpointSlice CRD missing from sysdump

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium-cli#1486]
If Cilium is running with `enable-cilium-endpoint-slice: true`, then we should capture this information.

**Comment by mritunjaysharma394** [comment]
Hi @christarazi, I would love to work on this if no one has started yet on it, let me know if it sounds great, thanks!

**Comment by christarazi** [comment]
@mritunjaysharma394 Yes please feel free to work on it!

**Comment by christarazi** [comment]
@mritunjaysharma394 Please reach out to #development if you need help on Cilium Slack.

**Comment by tklauser** [comment]
Support for gathering `CiliumEndpointSlice` resources in sysdumps was added in https://github.com/cilium/cilium-cli/pull/1468. Closing this issue.
