### ISSUE TITLE
`cilium upgrade` doesn't support `--chart-directory`

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium-cli#1493]
When upgrading to a specific set of images, it may be necessary to pass a new Helm chart to use (for example, see https://github.com/cilium/cilium/issues/24787). That is however not supported today in the `upgrade` command:
```
$ ./cilium upgrade --agent-image quay.io/cilium/cilium-ci:latest --operator-image quay.io/cilium/operator-generic-ci:latest --chart-directory=$CILIUM_SRC/install/kubernetes/cilium
unknown flag: --chart-directory
```

**Comment by chirag0002** [comment]
Hey @pchaigno, I've linked a PR resolving this issue. Do check it out and review it.
Correct me if something is missing.
