### ISSUE TITLE
Can't run connectivity tests on latest Cilium

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium-cli#1507]
```
$ ./cilium connectivity test
connectivity test failed: unable to determine if KNP feature is enabled: failed to parse Cilium version -dev:latest to semver
```
This is happening because I'm running that in one of the CI VMs where we compile the images locally from the latest sources.

Relying on the image tag to parse the Cilium version seems really fragile.

**Comment by pchaigno** [comment]
I see we have:
```
      --k8s-version string                                    Kubernetes server version in case auto-detection fails
```
Maybe we also need `--cilium-version`?

**Comment by tklauser** [comment]
> I see we have:
> 
> ```
>       --k8s-version string                                    Kubernetes server version in case auto-detection fails
> ```
> 
> Maybe we also need `--cilium-version`?

There is `--assume-cilium-version` which should achieve the same.

#1510 should also fix the auto-detection and incorporate the value specified with `--assume-cilium-version` for the KNP feature detection.
