### ISSUE TITLE
Helm mode install doesn't support AKS

### ISSUE THREAD

**Issue by meyskens** [cilium/cilium-cli#1566]
## Bug report

When installing Cilium on AKS with `CILIUM_CLI_MODE=helm` it will not work as `--azure-resource-group` is not implemented in this mode. 

**General Information**

- Cilium CLI version: v0.14.0

**How to reproduce the issue**
1. `CILIUM_CLI_MODE=helm cilium install --azure-resource-group "something"`

**Comment by michi-covalent** [comment]
💯 thanks for filing the issue @meyskens i'll take care of this.
