### ISSUE TITLE
Verify that `clustermesh externalworkloads` command still works under Helm mode

### ISSUE THREAD

**Issue by asauber** [cilium/cilium-cli#1623]
One subcommand which has not yet been tested under Helm mode, and appears to require no Helm-related changes is the `clustermesh externalworkloads` subcommand.

This subcommand is used to configure Cilium on a a machine which is not a member of a Kubernetes cluster, in order to participate in a clustermesh. It is not particularly easy to test this command interactively, as it requires the availability of some machine or virtual machine which is a not a member of a clustermesh but can connect to all instances of `clustermesh-apiserver` in the clustermesh.

The goal of this task is to set up such a machine and verify that it can still connect to the clustermesh after the mesh has been esablished using the new Helm-based implementations of `enable` and `connect` using the new methods for CA-cert generation and distribution.

**Comment by giorio94** [comment]
One aspect to be addressed here concerns the fact that support for [external workloads is not enabled by default](https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml#L2620-L2623) (which provides a few advantages IMHO, including possible better performance: https://github.com/cilium/cilium/pull/25259). `clustermesh externalworkloads` should likely check for that and enable it accordingly.

**Comment by asauber** [comment]
PR is up here https://github.com/cilium/cilium-cli/pull/1640

**Comment by michi-covalent** [comment]
completed in https://github.com/cilium/cilium-cli/pull/1640
