### ISSUE TITLE
Update CLI documentation for Helm mode

### ISSUE THREAD

**Issue by asauber** [cilium/cilium-cli#1624]
For the most part, documentation that relates to the Cilium CLI remains unchanged after the implementation of Helm mode.

There are a few notable changes that will need to be made:

- [ ] Initial Cilium/Documentation pass which updates references to the new Helm-mode version and replaces all instances of `cilium-cli` commands with their Helm mode equivalents. All instances where removed flags are used should be updated to use their `--helm-set` equivalents
- [ ] New Doc: All removed flags should be documented with alternative usage using `--helm-*` flags
- [ ] The nuances of `--reuse-values` and `--reset-values` should be clearly documented. 

When using `cilium upgrade` a user may need to render their existing values in order to avoid having many values reset. A general solution for this is a hotly discussed topic in the upstream Helm community. As part of this documentation, we should add comments to the codebase as appropriate to explain the situation as well.
    - A general recommendation to avoid the strange behavior of `--reuse-values` is to perform any upgrade in two steps. First, upgrade the chart version with no values provided. Then, upgrade any values with `--reuse-values` provided.
    - See these upstream issues:
      https://github.com/helm/helm/issues/8085
      https://github.com/helm/helm/pull/9653
      https://github.com/helm/helm/pull/9426
    - This blog post explains the issue well https://shipmight.com/blog/understanding-helm-upgrade-reset-reuse-values
    
![helm-upgrade-article table](https://github.com/cilium/cilium-cli/assets/2046750/19ca0ea2-ced0-4679-8d1e-8ac83dac77a1)

**Comment by christarazi** [comment]
@asauber Why did https://github.com/cilium/cilium/pull/26494 get closed?

**Comment by asauber** [comment]
It was closed in favor of https://github.com/cilium/cilium/pull/26606, which had the same (significant) edits.

**Comment by christarazi** [comment]
So should this issue be closeD?

**Comment by asauber** [comment]
The `--reuse-values` edge cases are not documented. However, that will eventually be covered, by https://github.com/cilium/cilium-cli/issues/1725, so I'll say yes.
