### ISSUE TITLE
Migrate all remaining cilium-cli workflows to run using Helm mode

### ISSUE THREAD

**Issue by asauber** [cilium/cilium-cli#1625]
As part of the Cilium CLI Helm mode implementation, a variety of the CI workflows were updated to run both a Helm-based implementation and "classic" implementation.

https://github.com/cilium/cilium-cli/blob/main/.github/workflows/gke.yaml#L41
https://github.com/cilium/cilium-cli/blob/main/.github/workflows/multicluster.yaml#L42

One of these was the first CI usage of the `cilium upgrade` subcommand.

https://github.com/cilium/cilium-cli/blob/main/.github/workflows/kind.yaml#L226

The goal of this task is to migrate all of the remaining workflows to use the Helm mode, in preparation for Helm mode becoming the default mode in the next release of `cilium-cli`

**Comment by michi-covalent** [comment]
opened draft PRs:

- eks: https://github.com/cilium/cilium-cli/pull/1638
- eks tunnel mode: https://github.com/cilium/cilium-cli/pull/1639
- external workloads: https://github.com/cilium/cilium-cli/pull/1640

@asauber i didn't touch https://github.com/cilium/cilium-cli/blob/main/.github/workflows/multicluster.yaml. i'm assuming you'll take care of it after https://github.com/cilium/cilium-cli/pull/1628 gets merged ✨

**Comment by asauber** [comment]
@michi-covalent multicluster was completed a while back https://github.com/cilium/cilium-cli/commit/41d8616942dde523026a38dd396b018d6d000cf5 :grin:

**Comment by michi-covalent** [comment]
oh wow things are moving at an amazing pace
