### ISSUE TITLE
Add --wait support for cilium hubble enable

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium-cli#164]
Similar to `cilium install`, `cilium hubble enable` should block until hubble is enabled successfully. The same `Status()` command can be called as is done for `install.`

**Comment by neel229** [comment]
I think I can do that.

**Comment by pchaigno** [comment]
@neel229 I assigned you. Don't hesitate to reach out on Slack (e.g., #development) if you have any question.

**Comment by neel229** [comment]
actually I made a pr, can someone check it out
