### ISSUE TITLE
hubble: Only patch ConfigMap and restart if required

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium-cli#165]
When enabling Hubble, only patch the ConfigMap and restart the Cilium pods when actually required.

**Comment by tklauser** [comment]
As a small hint, in case anyone wants to take this: the logic in `(*hubble.K8sHubble).disableHubble` here: https://github.com/cilium/cilium-cli/blob/7416ed66c8d019cc22c1913d9fb2ecabb9dd9f1f/hubble/hubble.go#L150-L170 could probably be reused to achieve this.

**Comment by tklauser** [comment]
Indeed, this was fixed as part of #1137. Thanks for the report @walbertus!

**Comment by tklauser** [comment]
Indeed, this was fixed as part of #1137. Thanks for the report @walbertus!
