### ISSUE TITLE
uninstall does not remove roles and role-binding for cilium-config-agent

### ISSUE THREAD

**Issue by aojea** [cilium/cilium-cli#1653]
## Bug report

Install and uninstall should be idempotent

**General Information**

- Cilium CLI version (run `cilium version`)
```
cilium version
cilium-cli: v0.12.8 compiled with go1.19.3 on linux/amd64
cilium image (default): v1.12.2
cilium image (stable): v1.13.2
cilium image (running): unknown. Unable to obtain cilium version, no cilium pods found in namespace "kube-system"
```
- Orchestration system version in use (e.g. `kubectl version`, ...)
- Platform / infrastructure information (e.g. AWS / Azure / GCP, image / kernel versions)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip: `cilium sysdump`

**How to reproduce the issue**

1. cilium install 
2. cilium uninstall
3. cilium install

Error: Unable to install Cilium: roles.rbac.authorization.k8s.io "cilium-config-agent" already exists

**Comment by ChrsMark** [comment]
This one should be fixed by https://github.com/cilium/cilium-cli/pull/1382. 

cc: @tklauser @giorio94
