### ISSUE TITLE
clustermesh: `cilium clustermesh status` fails if clusters are not connected yet

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium-cli#166]
`cilium clustermesh status` fails if clusters are not connected yet.

This is a regression due to #123, especially by commit https://github.com/cilium/cilium-cli/pull/123/commits/077d821c709a6f5959b376c665553fa9833df47c

**Comment by cmluciano** [comment]
+1 I would expect this to warn that it's not connected but not provide information about `cilium install` since I already have them set.
