### ISSUE TITLE
Rename CLI to ciliumctl

### ISSUE THREAD

**Issue by guettli** [cilium/cilium-cli#1676]
## Bug report

it is very confusing, that there are two commands called `cilium`.

The command in the container, and the cilium cli tool.

Please rename one of them. 

I would suggest to rename the cli tool to `ciliumctl`.

**Comment by tklauser** [comment]
There is a draft PR at https://github.com/cilium/cilium/pull/28085 to rename the per-node Cilium CLI to `ciliumctl`.

**Comment by tklauser** [comment]
The per-node `cilium` command was renamed to `cilium-dbg` for the upcoming Cilium v1.15 release, see https://github.com/cilium/cilium/pull/28085. I think we don't need to rename the clusterwide CLI tool to anything else. I'll thus close this issue.
