### ISSUE TITLE
Make `--helm-` options compatible with `helm install` command line in helm mode

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium-cli#1701]
## Proposal / RFE

Cilium-cli `install` command already accepts various helm options (e.g., `--helm-set`) that is like the `--set` option to `helm install`. Make `--set` an alias of `--helm set` when cilium cli is in helm mode, so that command line options are easy to copy/paste between `cilium install` (in helm mode) and `helm install`. This also allows to make Cilium documentation more coherent between the two install methods. Same for all the other `--helm` options, if possible.

Another discrepancy between the helm and non-helm mode is the `--version` option. In non-helm mode it needs to be specified as a (released) Cilium version, currently defaulting to `v1.13.3`. In helm mode, it needs to be the helm chart version, e.g., `1.13.3`. It might be clearer if there was a separate `--helm-version` option that turns on the helm mode and takes a helm chart version string? This would not be optimal if the helm mode is planned to made the default at some point, however, as this would add boilerplate that we are trying to reduce here for all the `--helm-*` options.

Another useful `helm install` option that is very useful for debugging helm chart behaviour and would be nice to have in `cilium install` is `--dry-run`, which, then used with `--debug` shows what resources are being created.

**Comment by michi-covalent** [comment]
✅  opened https://github.com/cilium/cilium-cli/pull/1739 to add aliases for `--helm-*` flags.

regarding `--version` flag, cilium-cli uses https://pkg.go.dev/github.com/blang/semver/v4?utm_source=godoc#ParseTolerant to parse the version, so it should work with or without `v` prefix. in other words, these 2 commands are equivalent:

```
cilium install --version 1.13.3
```
```
cilium install --version v1.13.3
```
