### ISSUE TITLE
Implement `cilium clustermesh disconnect` for Helm mode

### ISSUE THREAD

**Issue by asauber** [cilium/cilium-cli#1724]
Similar to https://github.com/cilium/cilium-cli/issues/1620 `clustermesh connect` implementation

Implement `cilium clustermesh disconnect` using Helm actions.

This is the help message for the non-Helm based existing command:

```
Disconnect from a remote cluster

Usage:
  cilium clustermesh disconnect [flags]

Flags:
      --destination-context string   Kubernetes configuration context of destination cluster
  -h, --help                         help for disconnect

Global Flags:
      --context string     Kubernetes configuration context
  -n, --namespace string   Namespace Cilium is running in (default "kube-system")
```

Let's implement the same set of flags (namely `--destination-context`). This command will remove the cluster identified by `--destination-context` from the Helm values of the cluster identified by `--context`, and then apply those Helm values using a helm `Upgrade` action.

**Note:** the name of the destination context and the "cluster name" of the destination context may be different (for example, in the case of kind, the context name would typically be `kind-c2` while the name of the cluster might be `c2`.

The implementation primarily needs to iterate through this array in the Helm values, and delete the destination context, then perform the Helm upgrade.

https://github.com/cilium/cilium-cli/blob/main/clustermesh/clustermesh.go#L2089

**Comment by ChrsMark** [comment]
Hey @asauber, I have started drafting sth at https://github.com/cilium/cilium-cli/pull/1743. Feel free to provide any early feedback :).
