### ISSUE TITLE
connectivity: Add --short and --long

### ISSUE THREAD

**Issue by brb** [cilium/cilium-cli#1735]
The `--long` runs all tests in the connectivity test suite, while `--short` - just a few to give a quick response whether basic connectivity is working in a cluster.

**Comment by aanm** [comment]
List for `--short`: L3/L4/L7 netpol + Cluster IP services

**Comment by brb** [comment]
No longer relevant because of this suggestion - https://github.com/cilium/cilium-cli/pull/1970#issuecomment-1805188516.
