### ISSUE TITLE
Mutual Auth: `cilium status --wait` needs to wait for SPIRE installation

### ISSUE THREAD

**Issue by mhofstetter** [cilium/cilium-cli#1821]
Currently, `cilium status` doesn't take the installation of SPIRE into account (context: Cilium mutual Auth). This results in `cilium status --wait` not waiting until SPIRE is successfully installed.

Proposal: `cilium status` should include the status of the SPIRE server (K8s DaemonSet) and SPIRE agent (K8s StatefulSet).

**Comment by meyskens** [comment]
I took a different approach than described here as waiting on the deployment does not guarantee the agents are connected and the identities being set up. I came on the idea to surface this in the agent status where it does know if it is fully connected and identified over gRPC which cannot happen if all identities for boostrapping are not there. This pre-work is done in https://github.com/cilium/cilium/pull/26896

**Comment by jspaleta** [comment]
@meyskens 
Hey, the Cilium side of the change looks like it landed in the 1.15.0-pre-0 release of cilium out today, so we have something to test against now if you want to land this change.

**Comment by meyskens** [comment]
Ready for review with v1.15 now vendored in https://github.com/cilium/cilium-cli/pull/1845/commits
