### ISSUE TITLE
Cilium CLI v.0.15.0 and later doesn't return running version for enterprise in Helm Mode

### ISSUE THREAD

**Issue by saintdle** [cilium/cilium-cli#1828]
- Cilium CLI version (run `cilium version`)
v0.15.0 and v0.15.2
- Orchestration system version in use (e.g. `kubectl version`, ...)
```Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.3
```
- Platform / infrastructure information (e.g. AWS / Azure / GCP, image / kernel versions)
-Kind

**How to reproduce the issue**

Cilium installed using Helm Chart

1. Run ```cilium version```
2. Cilium is not detected for a verson for enterprise install (pulled through into the cilium cli v0.15.0 enterprise version)
```cilium version
cilium-cli: v0.15.2 compiled with go1.20.4 on darwin/arm64
cilium image (default): v1.13.4
cilium image (stable): v1.13.4
cilium image (running): unknown. Unable to obtain cilium version, no cilium pods found in namespace "kube-system"
```
3. set ```export CILIUM_CLI_MODE=classic``` and version is returned
```cilium version
cilium-cli: v0.15.2 compiled with go1.20.4 on darwin/arm64
cilium image (default): v1.13.4
cilium image (stable): v1.13.4
cilium image (running): v1.13.4-cee.1
````

**Comment by macmiranda** [comment]
Happens with Cilium OSS too
