### ISSUE TITLE
Cilium CLI should validate the --version argument

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium-cli#187]
If you pass `--version 1.9.6` into the Cilium CLI, it will pass this directly into the image tag and fail to deploy Cilium (ImagePullBackoff) because the real version number for the image is `v1.9.6`. The CLI should validate the arg and either transparently add the `v` if not specified, or reject the user argument if it is specified in the wrong format.

**Comment by vosdev** [comment]
The example in the --help even shows the wrong syntax
```
sudo cilium upgrade --help
Upgrade Cilium in a Kubernetes cluster

Examples:
# Upgrade Cilium to the latest micro release:
cilium upgrade

# Upgrade Cilium to a specific version
cilium upgrade --version 1.9.5
```
