### ISSUE TITLE
Forced to change k8s cluster name as per regex.

### ISSUE THREAD

**Issue by rahulk789** [cilium/cilium-cli#1871]
## Bug report

Hey, just trying to get the cilium ingress controller on my k8s and I got this:

$ cilium install --version 1.13.4     --set kubeProxyReplacement=true     --set ingressController.enabled=true     --set ingressController.loadbalancerMode=dedicated
:crystal_ball: Auto-detected Kubernetes kind: EKS
:information_source:  Using Cilium version 1.13.4
:crystal_ball: Auto-detected cluster name: arn:....../EKS-Cluster
:crystal_ball: Auto-detected datapath mode: aws-eni
:x: Cluster name "/EKS-Cluster" is not valid, must match regular expression: `^[a-z0-9]([-a-z0-9]*[a-z0-9])$`
:leftwards_arrow_with_hook: Rolling back installation...
Error: Unable to install Cilium: invalid cluster name

 I really find it inconvenient to change the name of an already running eks cluster binded to other configurations just for the sake of installing the cilium ingress controller. If this is considered as an valid issue, im willing to fix it myself. Thanks.

**Comment by rahulk789** [comment]
Relevant comments from Amit in slack:

Hi, few things here.
Firstly you cannot add /  to the cluster-name this is a limitation from EKS
eksctl create cluster -f ./eks-config_ipv4.yaml 
2023-07-27 20:28:01 [▶]  role ARN for the current session is "arn:aws:iam::XXXXXXXXXXXXXXXXXXX"
Error: validation for /EKS-Cluster failed, name must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*
Yes, if you try to use cilium install --helm-set cluster.name=EKS-Cluster  that also doesn’t work and we hit the issue as you are seeing
🔮 Auto-detected Kubernetes kind: EKS
ℹ️  Using Cilium version 1.13.3
🔮 Auto-detected cluster name: EKS-Cluster-eu-west-2-eksctl-io
🔮 Auto-detected datapath mode: aws-eni
❌ Cluster name "EKS-Cluster-eu-west-2-eksctl-io" is not valid, must match regular expression: ^[a-z0-9]([-a-z0-9]*[a-z0-9])$
↩️ Rolling back installation...
Good part is this
If you try to pass the cluster name via helm that works cluster.name
helm install cilium cilium/cilium --version 1.13.4 \
  --namespace kube-system \
  --set eni.enabled=true \
  --set ipam.mode=eni \
  --set egressMasqueradeInterfaces=eth0 \
  --set tunnel=disabled \
  --set cluster.name=EKS-Cluster
NAME: cilium
LAST DEPLOYED: Thu Jul 27 21:40:45 2023
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
You have successfully installed Cilium with Hubble.

Your release version is 1.13.4.

For any further help, visit https://docs.cilium.io/en/v1.13/gettinghelp
cilium config view | grep cluster-name
cluster-name                               EKS-Cluster

**Comment by joestringer** [comment]
> x Cluster name "/EKS-Cluster" is not valid, must match regular expression: ^[a-z0-9]([-a-z0-9]*[a-z0-9])$

I think this is the key, the regex there is only including lower-case letters. Given that the helm option accepts uppercase as well, this might just be an oversight.

**Comment by rahulk789** [comment]
correct

**Comment by rahulk789** [comment]
should I make a pr? @joestringer

**Comment by joestringer** [comment]
Sure, that would be awesome!

**Comment by amitmavgupta** [comment]
Thanks @rahulk789

**Comment by asauber** [comment]
This codepath is used only if you are in the CLI "classic" mode (environment `CILIUM_CLI_MODE=classic`) 

If you're using the latest version of the CLI, you may want to try Helm mode. It uses an embedded Helm client.
