### ISSUE TITLE
ClusterMesh fails to connect

### ISSUE THREAD

**Issue by KrystianMarek** [cilium/cilium-cli#1878]
## Bug report
**General Information**

With cilium deployed via helm via sub chart `clustermesh connect` fails with
```shell
❯ cilium --namespace network-services clustermesh connect --destination-context admin@titan
❌ Unable to find Helm release for the target cluster

Error: Unable to connect cluster: release: not found
```

In my current setup, cilium is deployed with values https://github.com/equinix-labs/talos-on-equinix-metal/blob/gocy/apps/network-dependencies/values.jinja.yaml#L54 . Cluster mesh looks enabled, but nodes are not yet connected (on purpose).

```shell
❯ kubectl --namespace network-services get secrets
❯ cilium --namespace network-services clustermesh status
✅ Cluster access information is available:
  - 147.28.183.98:2379
✅ Service "clustermesh-apiserver" of type "LoadBalancer" found
🔌 Cluster Connections:
🔀 Global services: [ min:0 / avg:0.0 / max:0 ]
```

Is the secret https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/clustermesh-config/clustermesh-secret.yaml the only thing left for clusters to connect, or is there more to it ? 

- Cilium CLI version  v0.15.4
- Orchestration system version in use v1.27.3
- Platform / infrastructure information Talos (v1.4.6); kernel 6.1.35-talos
- Link to relevant artifacts:
- - https://github.com/equinix-labs/talos-on-equinix-metal/blob/gocy/apps/network-dependencies/values.jinja.yaml#L54
- - https://github.com/equinix-labs/talos-on-equinix-metal/blob/gocy/apps/network-dependencies/Chart.yaml#L10
- Generate and upload a system zip: [sysdump](https://drive.google.com/file/d/1far5wJD8ULdzOULLWUxIPg0iatBrlzff/view?usp=drive_link)

**How to reproduce the issue**

1. Deploy cilium via sub chart
2. Try to connect cluster mesh with `cilium clustermesh connect`

**Comment by KrystianMarek** [comment]
Hi, any updates on this ?

**Comment by RealArtemiy** [comment]
having the same issue, had to revert to cilium-cli v0.14.8
