### ISSUE TITLE
Deployment with Cilium v1.8.6 fails on GKE  

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium-cli#189]
I’m unable to successfully deploy Cilium on a GKE cluster at the moment. The cilium pods come up fine, but none of the managed pods do.

  `Warning  FailedCreatePodSandBox  22s (x4 over 26s)   kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container “f6ca5819eee5af8a48fd5f505182dd31a90e20737a60c16ca139a9ae4ce7e1b2” network for pod “kube-dns-6465f78586-llt4t”: networkPlugin cni failed to set up pod “kube-dns-6465f78586-llt4t_kube-system” network: unable to allocate IP via local cilium agent: [POST /ipam][502] postIpamFailure  range is full`

Steps to reproduce the issue - 

```
$ gcloud container clusters create <name> --image-type COS --num-nodes 2 --machine-type n1-standard-4 --zone <zone>
$ ./cilium install --version v1.8.6
```

@cmluciano reported similar problem when he tried running connectivity tests.

**Comment by rolinh** [comment]
Cilium v1.8 is no longer supported (older supported release is v1.10 as of today).
