### ISSUE TITLE
CI: connectivity test check-log-errors: Link not found

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium-cli#1894]
## CI failure

from a cilium-cli scheduled kind workflow run with cilium v1.14.0:

https://github.com/cilium/cilium-cli/actions/runs/5763408772/job/15625139472

- Copy-paste the output the test failure.

```
  ❌ Found 1 logs matching list of errors that must be investigated:
2023-08-04T14:55:27.946943329Z level=error msg="Link not found" device=lxc347d09aa7056 subsys=datapath-loader
  🐛 Finalizing Test check-log-errors
```
[cilium-sysdumps.zip](https://github.com/cilium/cilium-cli/files/12262115/cilium-sysdumps.zip)

**Comment by michi-covalent** [comment]
another one: https://github.com/cilium/cilium-cli/actions/runs/5792120557/job/15697942532

**Comment by michi-covalent** [comment]
another occurrence: https://github.com/cilium/cilium-cli/actions/runs/5806751648/job/15740266657

[cilium-sysdumps.zip](https://github.com/cilium/cilium-cli/files/12303331/cilium-sysdumps.zip)

**Comment by michi-covalent** [comment]
one more https://github.com/cilium/cilium-cli/actions/runs/5841891204/job/15842464838

[cilium-sysdumps.zip](https://github.com/cilium/cilium-cli/files/12327699/cilium-sysdumps.zip)

**Comment by michi-covalent** [comment]
another one https://github.com/cilium/cilium-cli/actions/runs/6304786593/job/17116889843?pr=1984

[cilium-sysdumps.zip](https://github.com/cilium/cilium-cli/files/12719623/cilium-sysdumps.zip)

**Comment by giorio94** [comment]
Another one: https://github.com/cilium/cilium-cli/actions/runs/6564555844/job/17831153648
Sysdump: [cilium-sysdumps.zip](https://github.com/cilium/cilium-cli/files/13039448/cilium-sysdumps.zip)

**Comment by michi-covalent** [comment]
one more 😿 https://github.com/cilium/cilium-cli/actions/runs/6857820846/job/18647581602?pr=2108

```
  Found "2023-11-14T01:26:06.147950722Z level=error msg=\"Link not found\" device=lxc7f44cc4ef69e subsys=datapath-loader" in logs 1 times

  Found "2023-11-14T01:26:06.150879461Z level=error msg=\"Link not found\" device=lxcd7f7547b283f subsys=datapath-loader" in logs 1 times

  Found "2023-11-14T01:26:06.151005727Z level=warning msg=\"JoinEP: Failed to attach program(s)\" containerID=d8c7454117 datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3634 error=\"getting interface lxcd7f7547b283f by name: Link not found\" file-path=3634_next/bpf_lxc.o identity=22463 ipv4=10.244.0.83 ipv6= k8sPodName=kube-system/hubble-ui-78b9fbc9cb-6qmlz subsys=datapath-loader veth=lxcd7f7547b283f" in logs 1 times

  Found "2023-11-14T01:26:06.151068905Z level=error msg=\"Error while rewriting endpoint BPF program\" containerID=d8c7454117 datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3634 error=\"getting interface lxcd7f7547b283f by name: Link not found\" identity=22463 ipv4=10.244.0.83 ipv6= k8sPodName=kube-system/hubble-ui-78b9fbc9cb-6qmlz subsys=endpoint" in logs 1 times

  Found "2023-11-14T01:26:06.151421122Z level=error msg=\"endpoint regeneration failed\" containerID=d8c7454117 datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3634 error=\"getting interface lxcd7f7547b283f by name: Link not found\" identity=22463 ipv4=10.244.0.83 ipv6= k8sPodName=kube-system/hubble-ui-78b9fbc9cb-6qmlz subsys=endpoint" in logs 1 times
```

[cilium-junits.zip](https://github.com/cilium/cilium-cli/files/13343645/cilium-junits.zip)
[cilium-sysdumps.zip](https://github.com/cilium/cilium-cli/files/13343646/cilium-sysdumps.zip)

**Comment by michi-covalent** [comment]
hit this in https://github.com/cilium/cilium-cli/pull/2136

https://github.com/cilium/cilium-cli/actions/runs/7039057768/job/19157302289?pr=2136

[cilium-junits.zip](https://github.com/cilium/cilium-cli/files/13506207/cilium-junits.zip)
[cilium-sysdumps.zip](https://github.com/cilium/cilium-cli/files/13506208/cilium-sysdumps.zip)

**Comment by giorio94** [comment]
Another one: https://github.com/cilium/cilium-cli/actions/runs/7259322671/job/19776234471?pr=2194

**Comment by giorio94** [comment]
Another one: https://github.com/cilium/cilium-cli/actions/runs/7459445768/job/20295468816?pr=2191

**Comment by michi-covalent** [comment]
another one 😢 https://github.com/cilium/cilium-cli/actions/runs/8068163331/job/22040261074
