### ISSUE TITLE
'cilium clustermesh enable' doesn't take Cilium version into account

### ISSUE THREAD

**Issue by bmcustodio** [cilium/cilium-cli#190]
```
$ cilium install --cluster-name cilium-1 --cluster-id 1 --version v1.10.0-rc0
$ cilium clustermesh enable --service-type NodePort
```

currently results in `quay.io/cilium/clustermesh-apiserver:v1.9.x` being used. I guess this is a result of

https://github.com/cilium/cilium-cli/blob/c4c1dbdeea9e836993209afa6ede8079555c3cd1/clustermesh/clustermesh.go#L171
https://github.com/cilium/cilium-cli/blob/c4c1dbdeea9e836993209afa6ede8079555c3cd1/defaults/defaults.go#L71
https://github.com/cilium/cilium-cli/blob/c4c1dbdeea9e836993209afa6ede8079555c3cd1/defaults/defaults.go#L90

Maybe we could somehow look at the version of Cilium currently deployed and use the corresponding tag before defaulting?

**Comment by giorio94** [comment]
Closing, as no longer relevant as the CLI now uses helm under the hood to enable clustermesh.
