### ISSUE TITLE
Improve error messages for "release not found"

### ISSUE THREAD

**Issue by asauber** [cilium/cilium-cli#1907]
In codepaths where the CLI might fail with `release not found`, such as 

```
Error: Unable to enable ClusterMesh: release: not found
```

we should include more information in this message to allow for a resolution.

In most cases, the user is working with a cluster without a Helm-based Cilium install, or they haven't specified the `--namespace`.

Instructing a retry with `CILIUM_CLI_MODE=classic` can also be included until full removal of classic mode.

**Comment by dhanusaputra** [comment]
hi, can I help with this please?

**Comment by network-charles** [comment]
I’m currently having this issue while attempting to enable clustermesh. What namespace are you referring to, “kube-system”?

**Comment by cnvergence** [comment]
I would like to help with that, as I encountered the issue already fixed in https://github.com/cilium/cilium-cli/issues/2274
I will work on this PR: https://github.com/cilium/cilium-cli/pull/2597
