### ISSUE TITLE
Cilium v1.13.1 install CNI plugin failed

### ISSUE THREAD

**Issue by DesireWithin** [cilium/cilium-cli#1911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I setup a generic `k8s  v1.26.2` by `kubeadm` on kvm `Ubuntu 22.04`, kernel version is `5.15.0-60-generic`
I want to install cilium `v1.13.1` as pod network.
Here is my step:
1. Download cilium-cli from  https://github.com/cilium/cilium-cli/releases/download/v0.13.1/cilium-linux-amd64.tar.gz
2. uncompress it to /usr/local/bin
3. run cilium install:
```
$> cilium install  --wait-duration 5m --helm-values helm.yaml
```
Here is my helm.yaml:
```yaml
image:
  repository: harbor.mycompany.net/k8s/cilium
  tag: v1.13.1
  useDigest: false
  pullPolicy: "IfNotPresent"
operator:
  image:
      repository: harbor.mycompany.net/k8s/cilium-operator
      tag: v1.13.1
      useDigest: false
      pullPolicy: "IfNotPresent"
```
4. cilium will show installation is success:
```
# notice this line
ℹ️  Using Cilium version 1.13.0    
...
ℹ️  helm template --namespace kube-system cilium cilium/cilium --version 1.13.0 --set cluster.id=0,cluster.name=kubernetes,encryption.nodeEncryption=false,image.pullPolicy=IfNotPresent,image.repository=harbor.mycompany.net/k8s/cilium,image.tag=v1.13.1,image.useDigest=false,kubeProxyReplacement=disabled,operator.image.pullPolicy=IfNotPresent,operator.image.repository=harbor.mycompany.net/k8s/cilium-operator,operator.image.tag=v1.13.1,operator.image.useDigest=false,operator.replicas=1,serviceAccounts.cilium.name=cilium,serviceAccounts.operator.name=cilium-operator,tunnel=vxlan
...
```
5. coredns or other pods can't be created because:
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "36b29...": plugin type="cilium-cni" name ="cilium" failed (add): failed to find plugin "cilium-cni" in path [/opt/cni/bin]  
```

I checked the hostpath `/opt/cni/bin`, there is no `cilium-cni`. But in the cilium agent pod, `cilium-cni` is exist in `/opt/cni/bin`, not exist in `/host/opt/cni/bin/`

I downgrade both cilium agent and operator to `v1.13.0`, this issue is gone. So I think this is a 1.13.1 version specific bug.

I can produce  this bug very easy by set image tag from v1.13.0 to v.1.13.1 or reinstall cilium.

### Cilium Version

cilium-cli: v0.13.1 compiled with go1.20 on linux/amd64
cilium image (default): v1.13.0
cilium image (stable): unknown      `#my servers are offline`
cilium image (running): v1.13.1

### Kernel Version

Linux app-infra-k8s-master01 5.15.0-60-generic cilium/cilium#66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:39:03Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:32:22Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

None

### Relevant log output

```shell
None
```

### Anything else?

I notice that cilium-cli only support v1.13.0 for now, (but its own version is v1.13.1):
```sh
$> cilium install --list-versions
v1.14.0-snapshot.0
v1.13.0 (default)
v1.13.0-rc5
v1.13.0-rc4
v1.13.0-rc3
v1.13.0-rc2
v1.13.0-rc1
v1.13.0-rc0
...
```

I checked `/opt/cni/bin` privilege on the host:
```sh
drwxrwxr-x 2 root root 4096 Mar 20 09:20 /opt/cni/bin/
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jqueuniet** [comment]
No more error either after upgrading to Cilium 1.14.0 and cilium-cli 0.15.5

**Comment by shapirus** [comment]
Same issue here with a fresh install of k8s 1.26.8 via kops 1.26 with Cilium 1.12.13.

Any idea of a workaround?

Using a newer version of Cilium doesn't work, because kops is trying to be smarter than the operator:

```
│ Error: spec.networking.cilium.version: Invalid value: "v1.11.14": Only version 1.12 is supported
```

(v1.11.14 is what I tested to work in my case on a different cluster.)

**Comment by joestringer** [comment]
Overall I think that this problem is caused by mixing an matching Helm charts and Cilium versions where one is older and the other is newer. I don't think it reproduces while using the latest cilium-cli or by installing directly via Helm with any recent version of Cilium for supported branches. If you're hitting this issue with an external installer such as kOps, I suggest reaching out to your upstream installer to verify that they are pulling in a new version of the Cilium Helm charts as well as Cilium image version.
