### ISSUE TITLE
Update Test.Fail() and friends to receive context.Context

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium-cli#2042]
`Test.failCommon()` needs to detect a SIGTERM signal from the user in order to cancel the --pause-on-fail if the user presses ctrl+c:

https://github.com/cilium/cilium-cli/blob/8a38f71407b8b8b47e504d668ca5a74d3dfa6998/connectivity/check/logging.go#L298

Rather than signing up for a new `SIGTERM` notification inside this function, ideally each test caller should pass the context down into `Fail()`, `Failf()`, `Fatal()`, `Fatalf()` so that the globally declared SIGTERM handler can trigger the cancel inside `failCommon()` automatically.

**Comment by AHB102** [comment]
@joestringer Is this issue still up for grabs ?

**Comment by joestringer** [comment]
Yep, feel free to post a PR and link to this issue in the PR.

**Comment by prashantrewar** [comment]
hey @joestringer, i would like to work on this issue, is this issue still up for grabs ?

**Comment by joestringer** [comment]
Hi @prashantrewar , I don't see any linked PRs in the breadcrumbs so it should be up for grabs. Next step is to propose a PR and include the `Fixes: #2042` tag inside the PR description body.

**Comment by AHB102** [comment]
@prashantrewar I had made the necessary changes, but forgot to make a PR, apologies !
