### ISSUE TITLE
Idempotent Cilium Install ?

### ISSUE THREAD

**Issue by lfundaro** [cilium/cilium-cli#205]
Just noticed that when issuing `cilium install` 2x in a row, the second execution fails because resources (service accounts, config maps, daemonsets, etc) have been created already. Is this intended ? 

How to reproduce:

`Release v0.5`
```
$> cilium install
...
...
✅ 
$> cilium install 
...
..
Error: Unable to install Cilium:  unable to create secret kube-system/hubble-server-certs: secrets "hubble-server-certs" already exists
```

From a security perspective, it could make sense to abort installation, i.e.: one could argue that the cluster has been compromised with a certificate that an attacker has access to and all cilium-related bytes can be read, so in this case it's good to abort the installation. If we want to abort installation, should we at least say why we are aborting ? From a users perspective, reading this message doesn't tell me much on what next steps I should take to fix this. 

P.S.: I opened a [PR](https://github.com/cilium/cilium-cli/pull/206) that goes for idempotent. No tests yet, since I'm not sure if idempotency is not intended here. Alternatively, we could add a friendly message. Let me know what you think.

Cheers !

**Comment by lfundaro** [comment]
closing as we don't need idempotency. The issue evolved into telling users to do a `cilium upgrade` if they are trying to `reinstall` cilium.

**Comment by lfundaro** [comment]
closing as we don't need idempotency. The issue evolved into telling users to do a `cilium upgrade` if they are trying to reinstall cilium.

**Comment by joestringer** [comment]
I'd like to reopen this feature request as it would simplify declarative approaches to defining the way that I want Cilium to be created in an environment. From the PR discussion, it looks like there is some desire still to do idempotency, it just needs to take into account that upgrading an existing environment should not replace secrets etc.
