### ISSUE TITLE
Dangerous effect of using --dry-run: makes unannounced changes to EKS cluster DaemonSets

### ISSUE THREAD

**Issue by krokofant** [cilium/cilium-cli#2161]
## Bug report
using --dry-run or --dry-run-helm-values does changes to eks aws-node. This should not be done, and while it is outputted to logs in code the logs are discarded when using --dry-run.

**General Information**
```
cilium-cli: v0.15.17 compiled with go1.21.4 on darwin/arm64
cilium image (default): v1.14.4
cilium image (stable): v1.14.4
```

Problematic code:
https://github.com/cilium/cilium-cli/blob/036d768db9768be6292ea8eb2cefd38e6485d277/install/install.go#L681C1-L694C4

**How to reproduce the issue**
1. Use EKS cluster
2. Run something similar to `cilium install --version 1.14.4 --values values-migration.yaml --dry-run-helm-values`
3. Watch how the node selector is changed

**Comment by tklauser** [comment]
Thanks for the report @krokofant. I've opened #2166 with a fix to no longer make any changes to the cluster in dry-run mode.

> and while it is outputted to logs in code the logs are discarded when using --dry-run.

This is intentional so the helm values can be written to stdout and easily be piped to other commands.
