### ISSUE TITLE
Add L7 connectivity tests

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium-cli#217]
Both ingress and egress are needed. We've had bugs specifically unique to either before (https://github.com/cilium/cilium/issues/15826).

**Comment by jrajahalme** [comment]
https://github.com/cilium/cilium-cli/pull/158 added policy testing support, and https://github.com/cilium/cilium-cli/pull/194 added ingress policy case. With these we have both ingress and egress L7 proxy connectivity tests. 

https://github.com/cilium/cilium-cli/pull/215 overhauls the testing framework which makes for painful rebases for now, hopefully we can merge this soon.

**Comment by christarazi** [comment]
Ah, I wasn't aware of that. So this issue should be closed then?

**Comment by ti-mo** [comment]
There's now #251, that adds an additional egress policy for client pods, although it's exercised with a test reaching out over the internet as well as to a local Pod.

Closing this for now, feel free to re-open if any further iteration is necesary.
