### ISSUE TITLE
Make Cilium CLI work with Cilium installed through helm with a non-default name

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium-cli#2274]
Quite a few Cilium CLI commands fail with a `release: not found` error if Cilium got installed through helm with a non-default name. 

For instance:

```
$ helm install -n kube-system cilium-break-cli cilium/cilium --version v1.14.5

$ cilium hubble enable
Error: Unable to enable Hubble: release: not found

$ cilium clustermesh enable --service-type LoadBalancer
Error: Unable to enable ClusterMesh: release: not found
```

This happens because we hardcode the default release name (for instance [here](https://github.com/cilium/cilium-cli/blob/976322c74b7f9a7808fcb10b7632270268730126/hubble/hubble.go#L854)). Instead, we should make it user-configurable, similarly to the namespace where Cilium is installed.

**Comment by prashantrewar** [comment]
hey @giorio94, I would like to work on this issue. Could you please guide me on this?

**Comment by giorio94** [comment]
Sure, the idea is to make the helm release name configurable through a flag, similarly to the [namespace case](https://github.com/cilium/cilium-cli/blob/mio%2Fexternal-workloads-drop-version-retrieval/internal/cli/cmd/cmd.go#L78).

I'd suggest starting with introducing the new flag (which defaults to the current value), and then look for all the usages of `defaults.HelmReleaseName` and replace them with the propagated parameter.

Feel free to reach out if you have more questions.

**Comment by prashantrewar** [comment]
@giorio94, [namespace case] link is broken. Are you pointing [this](https://github.com/cilium/cilium-cli/blob/main/internal/cli/cmd/cmd.go#L78)?

**Comment by giorio94** [comment]
> @giorio94, [namespace case] link is broken. Are you pointing [this](https://github.com/cilium/cilium-cli/blob/main/internal/cli/cmd/cmd.go#L78)?

Yep, sorry. Should be fixed now.

**Comment by littlejo** [comment]
@prashantrewar Do you have news about this issue?

**Comment by matthewhembree** [comment]
@prashantrewar I wasn't sure if you were actively working on this or if you were busy with other things. I checked for a existing fork.

Apologies for being impatient, but I was interested in using the fix.
