### ISSUE TITLE
Add Windows executable to built artifacts

### ISSUE THREAD

**Issue by nbusseneau** [cilium/cilium-cli#231]
Since we already have a Windows executable for Hubble CLI, this would allow complete CLI usage from Windows.

**Comment by rolinh** [comment]
For context, the reason why there's no Windows release binary currently is because the cilium logger is imported and is not compatible with Windows because of the reliance on the syslog package. Once building for Windows is fixed, creating a Windows release binary is trivial.

**Comment by tklauser** [comment]
https://github.com/cilium/cilium/pull/16600 should fix this on the `cilium/cilium` side. Once that PR is approved and merged and made its way into a stable release and that release is vendored into `cilium/ciliumn-cli` we should be able to provide Windows release binaries as well.

**Comment by tklauser** [comment]
Merging https://github.com/cilium/cilium/pull/16806 (which prepares the CIlium dependencies to build on Windows) accidentally closed this issue. We first need to vendor a Cilium release including these changes and actually build the Windows binaries, thus reopening the issue.
