### ISSUE TITLE
don't depend on github.com/xi2/xz

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium-cli#2374]
https://github.com/cilium/cilium/actions/runs/8180037886/job/22367286109?pr=31077 says:

```
The third party dependencies below are not allowed under the CNCF's IP policy:
  - github.com/xi2/xz (XZ)
```

cilium-cli indirectly depends on github.com/xi2/xz through github.com/mholt/archiver, which is used by sysdump to archive / unarchive. should be pretty straightforward to implement the same functionality with the standard libraries.

**Comment by sayboras** [comment]
Should be fixed by https://github.com/cilium/cilium-cli/pull/2382
