### ISSUE TITLE
Missing version on `cilium version --client` @ v0.16.0

### ISSUE THREAD

**Issue by lucasfcnunes** [cilium/cilium-cli#2395]
## Bug report

**General Information**

- NA

**How to reproduce the issue**

```
$ wget -O - https://github.com/cilium/cilium-cli/releases/download/v0.16.0/cilium-linux-amd64.tar.gz | tar -xvz -f - 'cilium'
$ ./cilium version --client                                                                                                  
cilium-cli:  compiled with go1.22.0 on linux/amd64
cilium image (default): v1.15.1
cilium image (stable): v1.15.1
```

Issue:
`cilium-cli:  compiled with go1.22.0 on linux/amd64` should be
`cilium-cli: v0.16.0 compiled with go1.22.0 on linux/amd64`

I think this bug is related to #2362.

**Comment by michi-covalent** [comment]
yes it's fixed in #2370. i'll close this issue once the new release is out 🚀🙏

**Comment by lucasfcnunes** [comment]
Duplicate of #2381

**Comment by michi-covalent** [comment]
v0.16.1 has been released with the fix 🚀🙏 https://github.com/cilium/cilium-cli/releases/tag/v0.16.1

```
% ./cilium version --client
cilium-cli: v0.16.1 compiled with go1.22.1 on linux/amd64
```
