### ISSUE TITLE
Warn/fail on long IPCache convergence times

### ISSUE THREAD

**Issue by ti-mo** [cilium/cilium-cli#247]
For https://github.com/cilium/cilium/issues/16302.

Commit 37d795c483bd861635a11c7592ea0136a7de77cc introduced a wait loop to watch for ipcache entries the test suite depends on. Currently, its timeout is set to 20 seconds, and exceeding it results in a testing error.

@gandro @jrajahalme Should this timeout be lowered? Anything else we could add here?

**Comment by gandro** [comment]
In my opinion, I think if IPCache updates takes longer than say 30 seconds, it should be a hard test failure, as this will also be noticeable to users. If we just warn and increase the timeout, I'm afraid the warnings will likely just be ignored by most developers.

**Comment by aditighag** [comment]
>The question is whether we should lower it to 10 seconds or less

This seems as random as the current configured duration. Currently, we have set an upper bound, but it'll be good to get some heuristics around what's acceptable or not, and catch regressions if any. I've opened #248 to start that discussion.

**Comment by ti-mo** [comment]
Alright, let's continue there then.
