### ISSUE TITLE
Track stats for ipcache propagation wait loop

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium-cli#248]
Commit 37d795c introduced logic to wait for ipcache entries to be populated. Currently, we set an upper bound on the timeout set in such loops, but it'll good to have some kind of heuristics to base the values on.  With large timeouts,  regressions in the code (e.g., the one fixed by #16381) are likely to go unnoticed.

Per [comment](https://github.com/cilium/cilium-cli/pull/215#discussion_r634461920), it'll be good to track wait times for test runs in order to catch potential regressions.

We currently don't have an infrastructure to track latencies such as # of retries, overall test duration, etc across CI test runs. I've opened this issue to start discussions around how we can add improvements in these areas as part of CI 3.0.

**Comment by ti-mo** [comment]
Possible duplicate of #247, prompted by discussion during weekly. Could we discuss there what sort of tracking is expected to be performed?

**Comment by aditighag** [comment]
#247 discusses whether wait loop duration should be lowered or not. I don't see how this issue duplicates that one. The linked comment in the description gives more details about what sort of tracking I'm proposing.
