### ISSUE TITLE
Install cilium to Cluster Without Internet Access

### ISSUE THREAD

**Issue by zkryakgul** [cilium/cilium-cli#2530]
I have a Kubernetes cluster on my intranet. This cluster has no internet access. I have my internal registry so that I can push Cilium's necessary images. How can I install Cilium to this cluster?

**Comment by xiaods** [comment]
step 1: load image 
```
quay.io/cilium/cilium:v1.14.4
quay.io/cilium/operator-generic:v1.14.4
```
step 2: install with cllium cli
```
 # cilium helm values https://github.com/cilium/cilium/tree/master/install/kubernetes/cilium
        $SUDO KUBECONFIG=/etc/${SYSTEM_NAME}/${SYSTEM_NAME}.yaml $BIN_DIR/cilium install --version=1.14.4 --set image.useDigest=false --set operator.image.useDigest=false --set ipam.operator.clusterPoolIPv4PodCIDRList="10.42.0.0/16" --set k8sServiceHost=${API_SERVER_IP};;
```
see my install script:
https://github.com/xiaods/k8e/blob/main/contrib/install.sh#L458
