### ISSUE TITLE
Cilium version v1.15.5 missing

### ISSUE THREAD

**Issue by DimitarStefanovMihov** [cilium/cilium-cli#2565]
Cilium version: v0.16.7 compiled with go1.22.2 on linux/amd64
Kubectl version: v1.28.2

How to reproduce the issue:
1. Try to install cilium v1.15.5 - cilium install --version v1.15.5
Error occurs: looks like "https://helm.cilium.io" is not a valid chart repository or cannot be reached: Get "https://helm.cilium.io/index.yaml": tls: failed to verify certificate: x509: certificate signed by unknown authority

2. List available version for install - cilium install --list-versions
v1.16.0-pre.2
v1.16.0-pre.1
v1.16.0-pre.0
v1.15.4 (default)
v1.15.3
v1.15.2
v1.15.1
v1.15.0
Version v.15.5 is missing
I am not able to install this version, which is the latest most stable one. Am I missing something ?
Thank you in advance for the help. Live long and prosper !

**Comment by littlejo** [comment]
```
cilium version
cilium-cli: v0.16.8 compiled with go1.22.3 on linux/amd64
cilium image (default): v1.15.5
cilium image (stable): v1.15.5
cilium image (running): 1.15.4
```

```
cilium install --list-versions | head
v1.16.0-pre.2
v1.16.0-pre.1
v1.16.0-pre.0
v1.15.5 (default)
v1.15.4
v1.15.3
v1.15.2
v1.15.1
v1.15.0
v1.15.0-rc.1
```
