### ISSUE TITLE
Surfacing Cilium error messages in `cilium status`

### ISSUE THREAD

**Issue by nvibert** [cilium/cilium-cli#2590]
When troubleshooting Cilium installation and deployments, users often rely on the Cilium CLI to check the overall health of the Cilium deployment. While very useful, it lacks the context and the valuable logs that are often available on the Cilium agents.

As an example: when installing Cilium with incorrect settings, you might see `fatal` error messages in the Cilium agent logs, such as:

``
time="2024-06-10T14:23:43Z" level=fatal msg="invalid daemon configuration: native routing cidr must be configured with option --ipv6-native-routing-cidr in combination with --enable-ipv6=true --enable-ipv6-masquerade=true --enable-ip-masq-agent=false --routing-mode=native" subsys=daemon
``

These logs can be very instructive but require the user to check the logs across multiple Cilium agents or on the Cilium operator(s). 

Could we append `cilium status` with logs of the `fatal` and `error` severity? This could be the default behaviour or when using a flag (`cilium status --show-logs` or something along the lines). This would be very helpful for operators of Cilium.

**Comment by brb** [comment]
:take-my-money:
