### ISSUE TITLE
upgrade: `cilium upgrade` does not patch the Hubble Relay image

### ISSUE THREAD

**Issue by kaworu** [cilium/cilium-cli#260]
When Hubble Relay has been installed (for example through `cilium hubble enable`), `cilium upgrade` doesn't update the Hubble Relay image to the upgraded version.

**Comment by GoGstickGo** [comment]
Do you want to have `cilium hubble upgrade` cmd or when one runs `cilium upgrade`  it should upgrade hubble as well if it installed ?

**Comment by rolinh** [comment]
@GoGstickGo Hubble Relay lives in the Cilium tree and depends on Cilium releases. I think the aim should thus be to handle the upgrade as part of `cilium upgrade`.

**Comment by GoGstickGo** [comment]
Roger that, thanks for the  clarification . @rolinh
