### ISSUE TITLE
External workloads - install-external-workload.sh

### ISSUE THREAD

**Issue by cccsss01** [cilium/cilium-cli#2617]
<!--

After using cilium cli to create install-external-workload.sh

the ./install-external-workload.sh on the VM just continually cycles *waiting for cilium daemon to come up"

Additionally looking at the install script, it doesn't populate the correct ip address and node port when using nodeport, it 

CLUSTER_ADDR=${2:-ip:port}

In testing it is grabbing the wrong ip address of the port exposed, looks to be grabbing the control node which is not exposing that port, as the clustermesh api server is exposed on a different ip on the worker node.

I've tested using loadbalancer and it still cycles as well.

**Comment by giorio94** [comment]
Hi @cccsss01, I'm closing this issue since it is empty. Feel free to reopen if not intentional.
