### ISSUE TITLE
CI: port forwarding super flaky on AKS

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium-cli#2642]
`kubectl port-forward` to hubble relay frequently dies while running connectivity tests on AKS. 

```
Error: Unable to port forward: unable to execute "kubectl port-forward -n kube-system svc/hubble-relay --address 127.0.0.1 4245:80": exit status 1
....❌ Unable to execute "kubectl port-forward -n kube-system svc/hubble-relay --address 127.0.0.1 4245:80":
 Forwarding from 127.0.0.1:4245 -> 4245
Handling connection for 4245
error: lost connection to pod
```
this error rarely happens on GKE or EKS. i'm disabling flow validation on AKS until we fix this issue 😞 

### ci failures:

- https://github.com/cilium/cilium-cli/actions/runs/9687204699/job/26731315565#step:12:1043

**Comment by chancez** [comment]
This could be related to https://github.com/cilium/cilium/issues/33145. It might be that we need to increase the timeout between relay and hubble, and/or improve the health checking of hubble/relay. I'm hypothesizing that in some situations, we port-forward to relay, but hubble becomes unavailable, which causes relay to fail its health check, which breaks the port-forward.
