### ISSUE TITLE
connectivity:  --test-concurrency flag doesn't work with --include-conn-disrupt-test

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium-cli#2678]
i guess we need to deploy test-conn-disrupt-server to all the namespaces? connectivity test fails with this error:
```
timeout reached waiting for deployment cilium-test-5/test-conn-disrupt-server to become ready (last error: deployments.apps "test-conn-disrupt-server" not found)
```

https://github.com/cilium/cilium/actions/runs/9902787358

**Comment by viktor-kurchenko** [comment]
@michi-covalent can I close this issue?
