### ISSUE TITLE
connectivity test: `cilium connectivity test` should delete pods before the test is done.

### ISSUE THREAD

**Issue by xlejo** [cilium/cilium-cli#269]
When the `cilium connectivity test` done successfully, the pods stayed in the cluster.

**Comment by ti-mo** [comment]
Hi @xlejo, thanks for the issue. This is indeed a bit inconvenient. `cilium uninstall` removes the `cilium-test` namespace, but that's probably not what you need. :slightly_smiling_face: 

I've created #275 that will address this issue, closing this one.
