### ISSUE TITLE
workflows: automatically bump Cilium version to latest stable when releasing

### ISSUE THREAD

**Issue by nbusseneau** [cilium/cilium-cli#272]
Follow-up to discussion in Jun 2 community meeting:

`cilium install` should default to installing the latest `stable` version of `cilium/cilium`, but we don't want to use the `quay.io/cilium/cilium:stable` because we need to have CLI versions pinning the Cilium version.

Proposed solution: have the [release workflow](https://github.com/cilium/cilium-cli/blob/41c027ead2571551a42d8b899212a583712a2ae8/.github/workflows/release.yaml) automatically find which is the latest `stable` version and then patch it in the CLI (see https://github.com/cilium/cilium-cli/pull/261 for example of which files to update).

This way we don't have to worry about managing versions: the CLI is always automatically pinned to the latest available `stable` Cilium version.

**Comment by kaworu** [comment]
> ... automatically find which is the latest stable version

AFAIK this is not possible to do automatically at the moment. This information is simply not available. At the moment, the latest stable version is v1.9.8 but `helm install` will install v1.10.0.

In Hubble, we have a [`stable.txt` file in the `master` branch](https://raw.githubusercontent.com/cilium/hubble/master/stable.txt) which contain the latest stable version.

**Comment by rolinh** [comment]
> At the moment, the latest stable version is v1.9.8 but helm install will install v1.10.0.

I'm confused. v1.10.0 **is** the latest stable version, not v1.9.8 :thinking:

**Comment by pchaigno** [comment]
> In Hubble, we have a stable.txt file in the master branch which contain the latest stable version.

Let's just add the same in cilium/cilium.

**Comment by kaworu** [comment]
> I'm confused. v1.10.0 is the latest stable version, not v1.9.8 thinking

@rolinh correct thank you, I was confused by the v1.10.0 release note which can be interpreted as "v1.9.7 is still the stable release".

**Comment by rolinh** [comment]
https://github.com/cilium/cilium/pull/16453 was merged which means that there's now a [`stable.txt` file](https://github.com/cilium/cilium/blob/master/stable.txt) at the root of cilium's git repo master branch that always points to the latest stable release.
