### ISSUE TITLE
Support opening hubble UI on non-mac platforms

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium-cli#287]
This line uses `open` to open the Hubble UI:

https://github.com/cilium/cilium-cli/blob/309c2a34257bb08e21fed9ef87b499e2d7016121/hubble/ui.go#L338

This works on OSX, but not on other platforms.

On Linux, I believe that we could alternatively try `xdg-open`.

**Comment by tklauser** [comment]
Noticed the same and sent PR #332 and only now noticed this issue. That PR fixes this using the `github.com/pkg/browser` package which essentially wraps `xdg-open` and other tools, depending on platform.
