### ISSUE TITLE
Implement `--flow-validation=disabled`

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium-cli#293]
Running the connectivity tests with `cilium connectivity test --flow-validation=disabled` doesn't seem to actually disable flow validation:
```
$ cilium connectivity test --flow-validation=disabled
[...]
✅ curl command "curl -w %***local_ip***:%***local_port*** -> %***remote_ip***:%***remote_port*** = %***response_code***\n --show-error --silent --fail --show-error --connect-timeout 5 --output /dev/null http://google.com" succeeded
❌ Flow validation failed for pod cilium-test/client-8655c47fd7-kfnhh: 3 failures (first: 0, last: 0, matched: 2, nlog: 5)
```
See https://github.com/cilium/cilium/runs/2748784336?check_suite_focus=true for details.

The following command also shows that it's not used anywhere apart from its definition :confused: 
```
$ git grep FlowValidationModeDisabled
connectivity/check/check.go:    case FlowValidationModeDisabled, FlowValidationModeWarning, FlowValidationModeStrict:
connectivity/check/check.go:    FlowValidationModeDisabled = "disabled"
```

I've marked this as `bug` because it looks like an oversight.

**Comment by michi-covalent** [comment]
i guess there are two PRs now, we can really make sure the validation is disabled 😄
