### ISSUE TITLE
Cilium CLI Connectivity Test DNS label missmatch

### ISSUE THREAD

**Issue by llivingstone** [cilium/cilium-cli#313]
Hi,

When using v1.20 of EKS, there is an ability to disable the AWS CoreDNS deployment is available in order to deploy your own. When doing this with the latest, public `coredns` Helm chart, the `k8s-app` label is `coredns` and not `kubedns` (https://github.com/coredns/helm/blob/master/stable/coredns/templates/deployment.yaml#L12)

The `client-egress-to-fqdns-google` Policy on the connectivity test requires the `k8s-app` label to be `kubedns` and therefore the test fails (https://github.com/cilium/cilium-cli/blob/v0.7/connectivity/manifests/client-egress-to-fqdns-google.yaml#L32).

Can both be added in to the policy?

**Comment by pchaigno** [comment]
Thanks for the report!

> Can both be added in to the policy?

I think that makes sense. Could you send a PR?

**Comment by llivingstone** [comment]
> Thanks for the report!
> 
> > Can both be added in to the policy?
> 
> I think that makes sense. Could you send a PR?

Of course i can, thanks!

**Comment by llivingstone** [comment]
https://github.com/cilium/cilium-cli/pull/320

**Comment by llivingstone** [comment]
This has been merged!
