### ISSUE TITLE
flake: timeout reached waiting for service (echo-same-node or echo-other-node)

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium-cli#342]
# flake instances

- https://github.com/cilium/cilium-cli/pull/331/checks?check_run_id=2861168613
- https://github.com/cilium/cilium-cli/runs/2842079516?check_suite_focus=true#341 
- https://github.com/cilium/cilium-cli/pull/336/checks?check_run_id=2860556736

# symptoms

`cilium connectivity test` times out waiting for echo-same-node or echo-other-node service.

```
⌛ [cilium-cilium-cli-950610632] Waiting for deployments [client client2 echo-same-node] to become ready...
⌛ [cilium-cilium-cli-950610632] Waiting for deployments [echo-other-node] to become ready...
⌛ [cilium-cilium-cli-950610632] Waiting for CiliumEndpoint for pod cilium-test/client-7b7bf54b85-blm9q to appear...
⌛ [cilium-cilium-cli-950610632] Waiting for CiliumEndpoint for pod cilium-test/client2-666976c95b-6zhqj to appear...
⌛ [cilium-cilium-cli-950610632] Waiting for CiliumEndpoint for pod cilium-test/echo-other-node-697d5d69b7-2nnln to appear...
⌛ [cilium-cilium-cli-950610632] Waiting for CiliumEndpoint for pod cilium-test/echo-same-node-7967996674-rt6hg to appear...
⌛ [cilium-cilium-cli-950610632] Waiting for Service cilium-test/echo-other-node to become ready...

Error: Connectivity test failed: timeout reached waiting for ***&Service***ObjectMeta:***echo-other-node  cilium-test /api/v1/namespaces/cilium-test/services/echo-other-node fd2c3c95-c8b4-48be-b159-1bdfb2041050 1725 0 2021-06-18 17:38:45 +0000 UTC <nil> <nil> map[kind:echo] map[] [] []  [***cilium Update v1 2021-06-18 17:38:45 +0000 UTC FieldsV1 ***"f:metadata":***"f:labels":***".":***,"f:kind":***,"f:spec":***"f:externalTrafficPolicy":***,"f:ports":***".":***,"k:***\"port\":8080,\"protocol\":\"TCP\"***":***".":***,"f:name":***,"f:port":***,"f:protocol":***,"f:targetPort":***,"f:selector":***".":***,"f:name":***,"f:sessionAffinity":***,"f:type":***]***,Spec:ServiceSpec***Ports:[]ServicePort***ServicePort***Name:echo-other-node,Protocol:TCP,Port:8080,TargetPort:***0 8080 ***,NodePort:30597,AppProtocol:nil,***,***,Selector:map[string]string***name: echo-other-node,***,ClusterIP:10.0.171.109,Type:NodePort,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:Cluster,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamily:nil,TopologyKeys:[],***,Status:ServiceStatus***LoadBalancer:LoadBalancerStatus***Ingress:[]LoadBalancerIngress***,***,***,***
```

**Comment by nbusseneau** [comment]
I've hit this in #336 as well: https://github.com/cilium/cilium-cli/actions/runs/950610632

**Comment by tklauser** [comment]
Seen on #540 as well.

https://github.com/cilium/cilium-cli/runs/3600185399?check_suite_focus=true
sysdump: https://github.com/cilium/cilium-cli/files/7170015/cilium-sysdump-out.zip.zip

**Comment by gandro** [comment]
Looking at the code that checks for the service, it seems to perform an `nslookup` on the service name to check. For some reason, that nslookup does not succeed.

A few thoughts about this:

- Should we enable `--debug` to log the error returned by nslookup? Can we do that in a test PR or do we need to do this globally?
- Can we collect coredns logs to check if coredns ever set up the service correctly?
- Given that this is actually a DNS lookup failing, are we maybe hitting #367 ?

**Comment by michi-covalent** [comment]
> Should we enable --debug to log the error returned by nslookup?

for some reason `nslookup -debug` always exit with a non-zero return code 😐 

> Can we collect coredns logs to check if coredns ever set up the service correctly?

sure, should this be a part of sysdump?

> Given that this is actually a DNS lookup failing, are we maybe hitting flake: allow-all/pod-to-world/http(s)-to-cilium-io fails #367 ?

yeah that's possible.

**Comment by gandro** [comment]
> > Should we enable --debug to log the error returned by nslookup?
> 
> for some reason `nslookup -debug` always exit with a non-zero return code neutral_face

Ah, I was actually thinking about running `cilium connectivity test --debug`, as it will give us the contents of stderr of nslookup. But it will make the test output a bit more noisy.

> sure, should this be a part of sysdump?

Probably. But I am a bit unsure about making this the default. While clearly useful in many contexts, coredns is not really Cilium related. Maybe add a `--capture-logs` option that collects logs for pods that match a certain label selector?

**Comment by tklauser** [comment]
> > > Should we enable --debug to log the error returned by nslookup?
> > 
> > 
> > for some reason `nslookup -debug` always exit with a non-zero return code neutral_face
> 
> Ah, I was actually thinking about running `cilium connectivity test --debug`, as it will give us the contents of stderr of nslookup. But it will make the test output a bit more noisy.

I think it should already be the case that we run connectivity tests with `--debug`, see #409. Might have missing some jobs though :thinking:

**Comment by gandro** [comment]
> I think it should already be the case that we run connectivity tests with `--debug`, see #409. Might have missing some jobs though thinking

Ah! Yes, you are correct. I was hitting and debugging this issue in `cilium/cilium` which does not have debug logs, but we do have some traces from `cilium/cilium-cli` with the error message. In that case no action needed regarding that point, we already do have the stderr (from https://github.com/cilium/cilium-cli/issues/342#issuecomment-919978939):

```
2021-09-14T14:55:43.345571900Z 🐛 Error waiting for service cilium-test/echo-other-node: command terminated with exit code 1: ^C
```

Not sure where that `^C` comes from :thinking:

**Comment by gandro** [comment]
> Not sure where that ^C comes from

So turns out this is the context cancellation (i.e. the timeout being hit, and we send a CTRL+C to terminate nslookup). So apparently nslookup timed out because it never received an answer (i.e. no NXDOMAIN, which I would expect).

From the client pod, we see a bunch of unanswered DNS queries leave:
```console
$ cat hubble-flows-cilium-4rl2f-20210914-145554.json| hubble observe --port 53                                 
Sep 14 14:55:23.443: cilium-test/client-6488dcf5d4-tb96w:50026 <> kube-system/kube-dns:53 from-endpoint FORWARDED (UDP)
Sep 14 14:55:23.443: cilium-test/client-6488dcf5d4-tb96w:50026 -> kube-system/kube-dns-b4f5c58c7-jkl9s:53 to-stack FORWARDED (UDP)
Sep 14 14:55:28.549: cilium-test/client-6488dcf5d4-tb96w:60098 <> kube-system/kube-dns:53 from-endpoint FORWARDED (UDP)
Sep 14 14:55:28.549: cilium-test/client-6488dcf5d4-tb96w:60098 -> kube-system/kube-dns-b4f5c58c7-jkl9s:53 to-stack FORWARDED (UDP)
Sep 14 14:55:33.549: cilium-test/client-6488dcf5d4-tb96w:60098 <> kube-system/kube-dns:53 from-endpoint FORWARDED (UDP)
Sep 14 14:55:33.549: cilium-test/client-6488dcf5d4-tb96w:60098 -> kube-system/kube-dns-b4f5c58c7-jkl9s:53 to-stack FORWARDED (UDP)
Sep 14 14:55:38.549: cilium-test/client-6488dcf5d4-tb96w:60098 <> kube-system/kube-dns:53 from-endpoint FORWARDED (UDP)
Sep 14 14:55:38.549: cilium-test/client-6488dcf5d4-tb96w:60098 -> kube-system/kube-dns-b4f5c58c7-jkl9s:53 to-stack FORWARDED (UDP)
```

I don't see any of these DNS packets arrive on the other node (where `kube-system/kube-dns-b4f5c58c7-jkl9s` is hosted) however. So it seems like the DNS packets are getting dropped by the stack? Or we are missing some flow logs.

**Comment by christarazi** [comment]
I incorrectly thought https://github.com/cilium/cilium-cli/pull/695 would fix this flake. I don't see us hitting this flake much anymore though. Could we close this issue?

cc @nbusseneau

**Comment by jinsiang2008** [comment]
+1 on this, we hit these issues a lot when we run the connectivity tests, maybe we could standardize the tests, and refine the outputs/indicators to show what's the problem, or potential fixes. Thanks.

**Comment by Rammurthy5** [comment]
Hiya, i face the same issue on cilium 1.14.4 running on kubernetes 1.28. Installed via helm, and VPC peered. 
Has this been fixed? does anyone know the workaround please?
