### ISSUE TITLE
flake: curl to nodeport fails with exit code 7

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium-cli#344]
# flake instances

- https://github.com/cilium/cilium-cli/runs/2861768000?check_suite_focus=true
- https://github.com/cilium/cilium-cli/pull/319/checks?check_run_id=2861173337

# symptoms

curl to nodeport (can be either a local or remote nodeport) fails with exit code 7 (Connect failed):
```
  ❌ command "curl -w %***local_ip***:%***local_port*** -> %***remote_ip***:%***remote_port*** = %***response_code*** --silent --fail --show-error --connect-timeout 5 --output /dev/null http://10.168.0.24:32193" failed: command terminated with exit code 7
```
and the subsequent flow validation fails.

**Comment by nbusseneau** [comment]
Hit in #339: https://github.com/cilium/cilium-cli/actions/runs/950721302
