### ISSUE TITLE
sysdump: Include stdout/stderr of `cilium sysdump` in sysdump

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium-cli#351]
When we ask users to retrieve a sysdump, we are sometimes missing information in the sysdump (such as bugtool reports) because errors happened. If we also collected the stdout and stderr of the `cilium sysdump` command in the sysdump itself, we would know exactly what errors were hit and could improve `cilium sysdump` or ask to retrieve a new sysdump.

**Comment by borkmann** [comment]
@tklauser could you or @sayboras take a look? Thx

**Comment by tklauser** [comment]
Should be fixed by #728
