### ISSUE TITLE
flake: timeout waiting for nodeports on EKS(ENI)

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium-cli#355]
# flake instances

- https://github.com/cilium/cilium-cli/runs/2889294353?check_suite_focus=true
- most of the recent failures in https://github.com/cilium/cilium-cli/actions/workflows/eks.yaml?query=event%3Aschedule++

# symptoms

connectivity check times out waiting for nodeports
```
⌛ [cilium-cilium-cli-962182561.us-east-2.eksctl.io] Waiting for NodePort 192.168.161.8:31469 (cilium-test/echo-other-node) to become ready...
⌛ [cilium-cilium-cli-962182561.us-east-2.eksctl.io] Waiting for NodePort 192.168.161.8:31991 (cilium-test/echo-same-node) to become ready...
⌛ [cilium-cilium-cli-962182561.us-east-2.eksctl.io] Waiting for NodePort 192.168.107.170:31991 (cilium-test/echo-same-node) to become ready...
⌛ [cilium-cilium-cli-962182561.us-east-2.eksctl.io] Waiting for NodePort 192.168.107.170:31469 (cilium-test/echo-other-node) to become ready...

Error: Connectivity test failed: timeout reached waiting for NodePort 192.168.107.170:31469 (cilium-test/echo-other-node)
```

# other notes

i recently added a pre-test check to make sure all the nodeports are open: https://github.com/cilium/cilium-cli/commit/cbded727c97810b813c2366949b883e1fc8e7546

this check seems to be failing pretty consistently on `EKS (ENI)`. i don't see this check failing nearly as frequently in other environments.

**Comment by michi-covalent** [comment]
steps to repro:

- follow https://docs.cilium.io/en/v1.10/gettingstarted/k8s-install-default/ to create an eks cluster and install cilium. use `cilium-cli: v0.8.1`.
- run the connectivity check:
   ```
   cilium hubble enable
   cilium hubble port-forward&
   cilium connectivity test
   ```
- `kubectl exec` into the client pod and try connecting to the nodeport of `echo-other-node` service. the client pod can connect to the nodeport of the local node but not to the remote node.

**Comment by errordeveloper** [comment]
I'm seeing this on GKE also: https://github.com/cilium/cilium/runs/3557961582?check_suite_focus=true

**Comment by tklauser** [comment]
Seen on #556: https://github.com/cilium/cilium-cli/pull/556/checks?check_run_id=3657524522
