### ISSUE TITLE
Hardcoded service DNS domain

### ISSUE THREAD

**Issue by GuillaumeSmaha** [cilium/cilium-cli#401]
New kube-dns test added in commit https://github.com/cilium/cilium-cli/commit/d3d89298bf0511a3aa9233d8d402ae7e083469e3 is failing on kubernetes installation using a custom service DNS domain because the domain is hardcoded in test:
https://github.com/cilium/cilium-cli/blob/8d0139bb8af6b885da71c4c1d0e14af41f901274/connectivity/check/deployment.go#L503

To reproduce:
Use `--service-dns-domain=custom-domain.local` when installing with kubeadm

**Comment by zhaojizhuang** [comment]
I think this issue can be closed by https://github.com/cilium/cilium-cli/pull/479

**Comment by tklauser** [comment]
> I think this issue can be closed by #479

Thanks. Let's close this issue then.

@GuillaumeSmaha please reply here or open a new issue in case you still see the problem.
