### ISSUE TITLE
version check doesn't work with cilium CI image tags

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium-cli#406]
cilium-cli relies on the image tag being in the format `vx.y.z` to detect cilium version being installed: https://github.com/cilium/cilium-cli/pull/397

this does not work with cilium CI workflows since they tag cilium images with commit SHAs: https://github.com/cilium/cilium/blob/master/.github/workflows/conformance-aks.yaml#L129

**Comment by tklauser** [comment]
I think this should work now that we have `--version` and `--base-version`, i.e. we can specify the commit SHA with `--version` and set the corresponding Cilium version with `--base-version`.

Feel free to reopen or comment here if you think this isn't working as intended.
