### ISSUE TITLE
Can cilium-cli support the install of the image tag of "latest"?

### ISSUE THREAD

**Issue by TrevorTaoARM** [cilium/cilium-cli#491]
Now I am doing some modification to the Cilium code and verification testing then, but I don't find the support for the built images with the tag "latest", so I would like ask if the cilium-cli can support that tag in a certain way.

I did some change to the current cilium-cli code to support this tag in my local environment, if it's useful I would like to check it.

**Comment by tklauser** [comment]
@TrevorTaoARM  You should already be able to do that with the current version. For example, something like `cilium install --agent-image quay.io/cilium/cilium-ci --operator-image quay.io/cilium/operator-generic-ci --version latest` will install the latest CI images.

**Comment by TrevorTaoARM** [comment]
> @TrevorTaoARM I think you should already be able to do that with the current version. For example, something like `cilium install --agent-image quay.io/cilium/cilium-ci --operator-image quay.io/cilium/operator-generic-ci --version latest` will install the latest CI images.

I checked the cmd you mentioned here with the latest cilium-cli, but it shows the error:
$ ./cilium install --agent-image quay.io/cilium/cilium --operator-image quay.io/cilium/operator-generic  --version latest
ℹ️  using Cilium version "latest"
🔮 Auto-detected cluster name: kubernetes
🔮 Auto-detected IPAM mode: cluster-pool
🔑 Generating CA...
......
🚀 Creating Service accounts...
🚀 Creating Cluster roles...
**Unable to parse the provided version "latest", assuming it's =1.10.0**
🚀 Creating ConfigMap for Cilium version 1.10.0...
...

I think the version of 1.10.0 here is not what I want.

**Comment by tklauser** [comment]
> > @TrevorTaoARM I think you should already be able to do that with the current version. For example, something like `cilium install --agent-image quay.io/cilium/cilium-ci --operator-image quay.io/cilium/operator-generic-ci --version latest` will install the latest CI images.
> 
> I checked the cmd you mentioned here with the latest cilium-cli, but it shows the error:
> $ ./cilium install --agent-image quay.io/cilium/cilium --operator-image quay.io/cilium/operator-generic --version latest
> ℹ️ using Cilium version "latest"
> 🔮 Auto-detected cluster name: kubernetes
> 🔮 Auto-detected IPAM mode: cluster-pool
> 🔑 Generating CA...
> ......
> 🚀 Creating Service accounts...
> 🚀 Creating Cluster roles...
> **Unable to parse the provided version "latest", assuming it's =1.10.0**
> 🚀 Creating ConfigMap for Cilium version 1.10.0...
> ...
> 
> I think the version of 1.10.0 here is not what I want.

This only refers to the version that is assumed for ConfigMap compatibility, see https://github.com/cilium/cilium-cli/blob/b66334031c4eac93821f858e77d3313d04073c22/install/install.go#L1320

The actual version being installed should still be `latest` if you check `cilium status`. Maybe we should make that log message a bit clearer as it could lead to confusion.

**Comment by TrevorTaoARM** [comment]
> > > @TrevorTaoARM I think you should already be able to do that with the current version. For example, something like `cilium install --agent-image quay.io/cilium/cilium-ci --operator-image quay.io/cilium/operator-generic-ci --version latest` will install the latest CI images.
> > 
> > 
> > I checked the cmd you mentioned here with the latest cilium-cli, but it shows the error:
> > $ ./cilium install --agent-image quay.io/cilium/cilium --operator-image quay.io/cilium/operator-generic --version latest
> > ℹ️ using Cilium version "latest"
> > 🔮 Auto-detected cluster name: kubernetes
> > 🔮 Auto-detected IPAM mode: cluster-pool
> > 🔑 Generating CA...
> > ......
> > 🚀 Creating Service accounts...
> > 🚀 Creating Cluster roles...
> > **Unable to parse the provided version "latest", assuming it's =1.10.0**
> > 🚀 Creating ConfigMap for Cilium version 1.10.0...
> > ...
> > I think the version of 1.10.0 here is not what I want.
> 
> This only refers to the version that is assumed for ConfigMap compatibility, see
> 
> https://github.com/cilium/cilium-cli/blob/b66334031c4eac93821f858e77d3313d04073c22/install/install.go#L1320
> 
> The actual version being installed should still be `latest` if you check `cilium status`. Maybe we should make that log message a bit clearer as it could lead to confusion.

Yes, I think the the current version check assumes the version "latest" to be an error case but still use it, but I think it's a normal case and we should process it as a special case in addition to the "1.xx.xx" format.

**Comment by tklauser** [comment]
> > > > @TrevorTaoARM I think you should already be able to do that with the current version. For example, something like `cilium install --agent-image quay.io/cilium/cilium-ci --operator-image quay.io/cilium/operator-generic-ci --version latest` will install the latest CI images.
> > > 
> > > 
> > > I checked the cmd you mentioned here with the latest cilium-cli, but it shows the error:
> > > $ ./cilium install --agent-image quay.io/cilium/cilium --operator-image quay.io/cilium/operator-generic --version latest
> > > ℹ️ using Cilium version "latest"
> > > 🔮 Auto-detected cluster name: kubernetes
> > > 🔮 Auto-detected IPAM mode: cluster-pool
> > > 🔑 Generating CA...
> > > ......
> > > 🚀 Creating Service accounts...
> > > 🚀 Creating Cluster roles...
> > > **Unable to parse the provided version "latest", assuming it's =1.10.0**
> > > 🚀 Creating ConfigMap for Cilium version 1.10.0...
> > > ...
> > > I think the version of 1.10.0 here is not what I want.
> > 
> > 
> > This only refers to the version that is assumed for ConfigMap compatibility, see
> > https://github.com/cilium/cilium-cli/blob/b66334031c4eac93821f858e77d3313d04073c22/install/install.go#L1320
> > 
> > The actual version being installed should still be `latest` if you check `cilium status`. Maybe we should make that log message a bit clearer as it could lead to confusion.
> 
> Yes, I think the the current version check assumes the version "latest" to be an error case but still use it, but I think it's a normal case and we should process it as a special case in addition to the "1.xx.xx" format.

I don't think we currently need to treat it as a special case as the `ConfigMap` values for current `latest` are still the same as for 1.10.x as far as I can tell. Or are you seeing any differences?

**Comment by pchaigno** [comment]
@tklauser It would be nice to avoid the `Unable to parse the provided version "latest", assuming it's =1.10.0` error though.

**Comment by tklauser** [comment]
> @tklauser It would be nice to avoid the `Unable to parse the provided version "latest", assuming it's =1.10.0` error though.

@pchaigno Agree, that's what I meant with my comment "Maybe we should make that log message a bit clearer as it could lead to confusion." above. Do yout think we should avoid the error altogether or only in case of the version being set to `latest`?

**Comment by pchaigno** [comment]
Ah, I had missed that. Sorry.

I think we need to at least clarify the impact of the parsing failure since you said it won't impact the actual installed version. I would also just skip that message for `latest` if we think that's a common case, but that's nitpicking IMO.

**Comment by TrevorTaoARM** [comment]
Yes, I think the version of "latest" should be thought as normal, as the images built locally are tagged as "latest", so we can check them naturally and quickly.

**Comment by TrevorTaoARM** [comment]
Do you think it's helpful to add a special process to the version of "latest"?
