### ISSUE TITLE
Add encryption validation in connectivity test

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium-cli#50]
Blocked:
- Requires release of fix https://github.com/cilium/cilium/pull/14677

Tasks
- [ ] Detect if encryption is enabled (endpoints / nodes)
- [ ] Validate that non-local traffic is encrypted properly by checking the `Encrypted` field in the Hubble flow logs

**Comment by brb** [comment]
I think we can close this, as https://github.com/cilium/cilium-cli/pull/1241 added encryption validation tests (checks with tcpdump whether Cilium DP doesn't leak unencrypted traffic).
