### ISSUE TITLE
Install with CLI fails, works with Helm

### ISSUE THREAD

**Issue by drzero42** [cilium/cilium-cli#505]
I have a Talos cluster, which due to it's nature does not contain most commands, normally available on hosts. When I use Cilium CLI v0.8.6 to deploy Cilium v1.10.3, it will have an init-container for the cilium-agent daemonset, which is called `ebpf-mount`. This init-container fails (Exit code 127). If I deploy Cilium v1.10.3 with Helm, it works and the daemonset does not contain that init-container.

Would it be possible to have the Cilium CLI deploy the same daemonset that the Helm chart does?

**Comment by smira** [comment]
Looks like this might be related: https://github.com/cilium/cilium/issues/17883
