### ISSUE TITLE
Add support for Cilium to be installed on a Cluster API-managed

### ISSUE THREAD

**Issue by aanm** [cilium/cilium-cli#580]
See Scott's [blogpost](https://blog.scottlowe.org/2021/10/07/installing-cilium-via-clusterresourceset/) for the tutorial, it should be relatively easy to add support for an automatic installation by detecting this cluster type.

**Comment by harshitasao** [comment]
Hi @aanm  I want to work on this issue.

/assign

**Comment by aanm** [comment]
Hey @harshitasao I haven't seen anyone asking for this feature since the GitHub issue was created two years ago. You are free to work on it but I think there are other GitHub issues more interesting. Let me know if you still want to work on this, if you changed and decide to work on another issue I'll close this one.

**Comment by harshitasao** [comment]
Hey @aanm ! I'll assign myself to other issues. You may close this one. Thanks!
