### ISSUE TITLE
install: allowing `install` over interrupted previous installation

### ISSUE THREAD

**Issue by nbusseneau** [cilium/cilium-cli#589]
## Bug report

If `cilium install` is abruptly interrupted while in progress, the [rollback code](https://github.com/cilium/cilium-cli/blob/bcc992b93cce627c4505de25cbb207164b90390c/install/install.go#L1717-L1727) does not have a chance to run and there are leftover resources.

One solution could be to have `cilium install` be more lenient with existing resources and accepting them as-is or editing them instead of failing when they are already present.

- Detected in #584.
- Related to #149.

**How to reproduce the issue**

1. Run `cilium install`
2. Have it abruptly interrupted (e.g. kill process) while in progress
3. Run `cilium install` again
4. Fails due to partially installed resources (e.g. `hubble-server-certs`)

**Comment by xiaods** [comment]
my first install is successful, when i install agagin, it report error sucks
