### ISSUE TITLE
Error on `cilium context` when `$KUBECONFIG` requires root privileges

### ISSUE THREAD

**Issue by brumhard** [cilium/cilium-cli#617]
## Bug report

Hi I'm having issues to install cilium on a k3s node.
By default, the kubeconfig in `/etc/rancher/k3s/k3s.yaml` is created with `700` permissions.
That's why for running stuff like `kubectl` it's required to run with `sudo`, which works perfectly fine in the case of `kubectl`.
`cilium context/install` on the other hand won't work like this.
I know a simple workaround would be changing the file's permissions, but I thought it might be good to report anyway since it works for `kubectl` and I think it's valid to have restricted access to the kubeconfig.

**General Information**

- Cilium CLI version (run `cilium version`)
```
cilium-cli: v0.9.3 compiled with go1.17.3 on linux/amd64
cilium image (default): v1.10.5
cilium image (stable): v1.10.5
cilium image (running): unknown. Unable to obtain cilium version, no cilium pods found in namespace "kube-system"
```
- Platform / infrastructure information (e.g. AWS / Azure / GCP, image / kernel versions): k3s

**How to reproduce the issue**

1. `sudo chmod 700 $KUBECONFIG`
2. `sudo cilium context`

output on my machine
```
ubuntu@node1:~$ echo $KUBECONFIG
/etc/rancher/k3s/k3s.yaml
ubuntu@node1:~$ cilium context
unable to create Kubernetes client: error loading config file "/etc/rancher/k3s/k3s.yaml": open /etc/rancher/k3s/k3s.yaml: permission denied

ubuntu@node1:~$ sudo echo $KUBECONFIG
/etc/rancher/k3s/k3s.yaml
ubuntu@node1:~$ sudo cilium context
Context:
❌ Context  not found in configuration
```

**Comment by tklauser** [comment]
Thanks for your report @brumhard.

Is `$KUBECONFIG` set in root's environment? I think in the command you posted involving `$KUBCONFIG`, the variable is evaluated before running `sudo`. By default, environment variables are not inherited when using `sudo`, so I assume `$KUBECONFIG` to be empty when you run `sudo cilium context`. Does it work if you run `cilium` using `sudo KUBECONFIG=$KUBECONFIG cilium context` or `sudo --preserve-env=KUBECONFIG cilium context`?

**Comment by brumhard** [comment]
Hi @tklauser,
thank you very much. I knew it would be some stupid shell mistake 😄 
Worked as expected with your proposals 👍🏻
