### ISSUE TITLE
sysdump bugtool download fails for large files

### ISSUE THREAD

**Issue by gandro** [cilium/cilium-cli#654]
For large bugtool output files downloading the file via `kubectl exec cat` seems to fail on some K8s apiserver instances:

```
⚠️ Failed to unarchive 'cilium-bugtool' output for "cilium-agent-tl2s9": reading file in tar archive: /redacted/cilium-sysdump-20211209-173133/cilium-bugtool-cilium-agent-abcde-20211209-173040/cmd/cilium-bpf-ct-list-global.md: writing file: unexpected EOF
```

The file was correctly created on the pod, and could be downloaded manually.

Instead of `cat`ing very large files, we should probably try to split the file into smaller chunks and download them individually (including potentially adding a retry logic). Legacy sysdump (which uses `kubectl cp`) also failed in this particular instance.

**Comment by pchaigno** [comment]
Duplicate of https://github.com/cilium/cilium-cli/issues/616?

**Comment by michi-covalent** [comment]
> The file was correctly created on the pod, and could be downloaded manually.

@gandro just curious how did you download it manually? :eyes:

**Comment by gandro** [comment]
> > The file was correctly created on the pod, and could be downloaded manually.
> 
> @gandro just curious how did you download it manually? eyes

I believe the user accessed the node via ssh and fetched it from the host namespace.

**Comment by gandro** [comment]
> Duplicate of #616?

Kind of. Seems to be a different symptom (here, unarchive fails, while in #616 it's the actual download that fails), but the end result and fix looks to be the same. I'll close this one.
