### ISSUE TITLE
K3s support for cilium-cli

### ISSUE THREAD

**Issue by jamesharr** [cilium/cilium-cli#669]
## Proposal / RFE

**Is your feature request related to a problem?**

yes - we use k3s for an on-prem install and we'd like to use cilium as well. The documentation for installing cilium shows the CLI as the recommended way to install cilium, however the tool does not K3s as supported.

**Describe the solution you'd like**

Update documentation to reflect support. If needed, a note could be added that K3S is supported, but not tested.

**Comment by jamesharr** [comment]
I may have jumped the gun here, but it seems like `cilium-cli` might work just fine.

For some reason cilium-cli wasn't finding my cluster. I implemented a work-around using this.
```
mkdir ~/.kube
kubectl config view --raw=true > ~/.kube/config
chmod 0600 ~/.kube/config
# - comment out certificate-authority-data
# - add `    insecure-skip-tls-verify: true` just under `server: https://127.0.0.1:6443`
```

**Comment by jamesharr** [comment]
Yup, this was just my mistake - When I originally explored this, I had my `KUBECONFIG` set, but not exported, so cilium was never seeing it.

Is k3s officially supported? Maybe the main page of this project just needs to be updated?

**Comment by tklauser** [comment]
Thanks for the report. I assume you followed the getting started guide from the Cilium docs: https://docs.cilium.io/en/v1.11/gettingstarted/k8s-install-default/?

Is there anything in the guide that you think needs correction or clarification?

As far as `cilium-cli` is concerned, k3s is supported but currently not covered by CI. Same for Cilium itself. We usually test some of these k8s distributions/platforms (e.g. k3s) manually before a new release. It seems installation and single node tests worked on k3s, but there [was an issue](https://github.com/cilium/cilium/issues/18079) in connectivity tests with two nodes.

> Is k3s officially supported? Maybe the main page of this project just needs to be updated?

I think we can just update the README of this project to mention k3s as supported. Happy to take a PR in case you want to send one.

**Comment by jamesharr** [comment]
I got it working a little a bit before you responded, ty for taking a look.

**Comment by Demonsthere** [comment]
@jamesharr How exactly did you get it to work? I have been trying to install cilium via the cli on my k3d cluster the following way: 

```bash
docker exec k3d-server-0 sh -c "mount bpffs /sys/fs/bpf -t bpf && mount --make-shared /sys/fs/bpf"
kubectl taint nodes k3d-server-0 node.cilium.io/agent-not-ready=true:NoSchedule --overwrite=true
cilium install --context k3d --wait false --config wait-bpf-mount=false --wait-duration 0s
```

However, the cilium pod is stuck in init phase with 

```
sh: mount: not found
Mounting eBPF filesystem...
sh: mount: not found
```

On the server node fs i can see that the mount point in mount exists and is ready to be used
```
$ mount
none on /sys/fs/bpf type bpf (rw,relatime)
```

**Comment by jamesharr** [comment]
@Demonsthere , I was running k3s on top of Alma Linux 8.5 (CentOS clone) in a VM; not inside a container. Alma had bpfs mounted already.

I had tried installing Cilium on top of Alma inside an LXC container (via ProxMox VE) and something about BPFS inside a nested container just wasn't getting along. Unfortunately I didn't resolve it and didn't keep and notes because I figured that was probably a long shot working in the first place.

As a side note, I did need to turn off FirewallD. When it was enabled, it caused several problems inside the overlay. And the work around most listed in forum posts of enabling IP masq through firewall-cmd made things work, but really screwed up any NetworkPolicy -- from the pod's perspective, any traffic that came in from another node was NATd to the local node's address (10.42.x.1) so any firewall rule went out the window. That didn't show up on a tcpdump inside the pod, so I spent some time questioning my sanity until I noticed the source address when adding -v to netcat while in listen mode.

If you do get it to work inside of k3d, please do post somewhere because I'd be interested

**Comment by Demonsthere** [comment]
I actually managed to get cilium working on my k3d cluster, but there are some rough corners:

 1. Create the cluster
 ```bash
 k3d cluster create --image ${K3SIMAGE} --registry-use k3d-localhost -p "9090:30080@server:0" \
			-p "9091:30443@server:0" foobar \
--k3s-arg=--kube-apiserver-arg="enable-admission-plugins=PodSecurityPolicy,NodeRestriction,ServiceAccount@server:0" \
--k3s-arg="--disable=traefik@server:0" \
--k3s-arg="--disable-network-policy@server:0" \
--k3s-arg="--flannel-backend=none@server:0" \
--k3s-arg=feature-gates="NamespaceDefaultLabelName=true@server:0"
```
2. Create the bpffs ahead of installing cilium:
```bash
docker exec k3d-foobar-server-0 sh -c "mount bpffs /sys/fs/bpf -t bpf && mount --make-shared /sys/fs/bpf"
```
3. Taint nodes
```bash
kubectl taint nodes k3d-foobar-server-0 node.cilium.io/agent-not-ready=true:NoSchedule --overwrite=true
```
4. The funny part. Install cilium using helm with the following values, then wait for it to fail due to missing cgroupv2 mount and create that mount. We cannot create it beforehand, because cilium is expecting it to be available in /run
```yaml
setValues:
  externalIPs.enabled: true
  nodePort.enabled: true
  hostPort.enabled: true
  hubble.relay.enabled: true
  hubble.ui.enabled: true
```
```bash
		until bash -c "kubectl get pods -n kube-system -l k8s-app=cilium | grep 'Init:CreateContainerError'"; do \
			kubectl get pods -n kube-system -l k8s-app=cilium | grep "Running"; \
			is_running=$${?}; \
			if test $${is_running} -eq 0; then \
				break; \
			else \
				sleep 5; \
			fi; \
		done
		docker exec k3d-foobar-server-0 sh -c "mount --make-shared /run/cilium/cgroupv2"
```

With this I was able to get a working setup running, **however**:
- on my Mac and docker4mac this is working as expected
- a colleague, running ubuntu reported problems with not being able to recreate the setting (startup, teardown, startup again)
- our CI, also running ubuntu was not able to curl any service exposed by the cluster (without cilium it worked fine)
- don't let me get started to GKE dataplane v2...

I have to say, this is quite the adventure...

**Comment by raphink** [comment]
I'm seeing the same issue running Cilium in a k3d cluster, where the agent's `ebpf-mount` init container fails with:

```
sh: mount: not found
```

I managed to log into that init container, and found that indeed, `/usr/bin/mount` is absent. In fact, `/usr` is rather empty:

```
# ls /usr/
libexec
```

This is very surprising, because if I launch the exact same image with Docker, `/usr/bin/mount` works fine (and `/usr` is quite full):

```
❯ docker run --rm -ti quay.io/cilium/cilium:v1.11.2@sha256:4332428fbb528bda32fffe124454458c9b716c86211266d1a03c4ddf695d7f60 mount
overlay on / type overlay (rw,relatime,lowerdir=/var/lib/docker/overlay2/l/RVNMOVON4PZLH2T63BJUPCUORR:/var/lib/docker/overlay2/l/GLCILOFUKT34HJRNJJ4FAYNV64:/var/lib/docker/overlay2/l/U6PZOYWZQQVQQPKBDGCS56B2AQ:/var/lib/docker/overlay2/l/E6DNCGQPYXIC6SQC2IKZQYKW5B:/var/lib/docker/overlay2/l/CDB77LLWEEOWCDO2OXS4M4HGFK:/var/lib/docker/overlay2/l/YEHF4Q26ZKSJLY5W4ZT7SMPCLI:/var/lib/docker/overlay2/l/KJLUA5FBPCGC43VS5TRSKMGCLD:/var/lib/docker/overlay2/l/IGTN5GBKPXRSZK73YPW5J5THKK,upperdir=/var/lib/docker/overlay2/c5d14eb98be1489facb9eb11c5a0e900e5e863547ebb5acc3a0ac4bd51990f66/diff,workdir=/var/lib/docker/overlay2/c5d14eb98be1489facb9eb11c5a0e900e5e863547ebb5acc3a0ac4bd51990f66/work)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,size=65536k,mode=755,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup type cgroup2 (ro,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k,inode64)
/dev/mapper/vgubuntu-root on /etc/resolv.conf type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/vgubuntu-root on /etc/hostname type ext4 (rw,relatime,errors=remount-ro)
/dev/mapper/vgubuntu-root on /etc/hosts type ext4 (rw,relatime,errors=remount-ro)
devpts on /dev/console type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
proc on /proc/bus type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/fs type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/irq type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/sys type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/sysrq-trigger type proc (ro,nosuid,nodev,noexec,relatime)
tmpfs on /proc/asound type tmpfs (ro,relatime,inode64)
tmpfs on /proc/acpi type tmpfs (ro,relatime,inode64)
tmpfs on /proc/kcore type tmpfs (rw,nosuid,size=65536k,mode=755,inode64)
tmpfs on /proc/keys type tmpfs (rw,nosuid,size=65536k,mode=755,inode64)
tmpfs on /proc/timer_list type tmpfs (rw,nosuid,size=65536k,mode=755,inode64)
tmpfs on /proc/scsi type tmpfs (ro,relatime,inode64)
tmpfs on /sys/firmware type tmpfs (ro,relatime,inode64)
```

I can't find what causes this `/usr` directory to be empty, as it doesn't seem to come from the Pod spec.
