### ISSUE TITLE
CLI doesn't upgrade clustermesh-apiserver...

### ISSUE THREAD

**Issue by seimic** [cilium/cilium-cli#689]
Hi,

not sure if this is correct but I wonder a bit because of the results of an upgrade from 1.10.5 to 1.10.7.
The upgrade didn't touch the clustermesh-apiserver at all. Do I need to reinitialize the clustermesh 
after upgrades?

Versions: 
- cilium-cli: v0.10.1 compiled with go1.17.6 on windows/amd64
- cilium image (running): v1.10.7

Status (image versions) after upgrade from 1.10.5 to 1.10.7:
```sh
Image versions    cilium                   quay.io/cilium/cilium:v1.10.7: 6
                  cilium-operator          quay.io/cilium/operator-generic:v1.10.7: 1
                  clustermesh-apiserver    quay.io/coreos/etcd:v3.4.13: 1
                  clustermesh-apiserver    quay.io/cilium/clustermesh-apiserver:v1.10.5: 1
```
Clustermesh api-server is still version 1.10.5

Kind regards,
Michael

**Comment by tklauser** [comment]
Thanks for the report @seimic. Indeed it looks like currently `cilium upgrade` will only upgrade the `cilium` DaemonSet and the `cilium-operator` Deployment. I think the command should also check whether `clustermesh-apiserver` and/or `hubble-relay` are installed and need to be upgrade.

Possibly also related: #190, #260
