### ISSUE TITLE
cilium install fail on k3s ubuntu - Cluster name "" is not valid

### ISSUE THREAD

**Issue by asloan7** [cilium/cilium-cli#696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Can't install cilium on brand new ubuntu 20.04 with k3s
Following this https://docs.cilium.io/en/v1.10/gettingstarted/k3s/

First, with no CNI, node is not ready
kubectl get nodes
NAME                                 STATUS     ROLES                       AGE   VERSION
corti2623-awse1pi-1d.corticore.net   NotReady   control-plane,etcd,master   19m   v1.20.15+k3s1

Due to pods stuck in pending state (no CNI)
kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE
kube-system   coredns-6488c6fcc6-p4crr                  0/1     Pending   0          9m31s
kube-system   local-path-provisioner-5ff76fc89d-lprrr   0/1     Pending   0          9m31s
kube-system   metrics-server-86cbb8457f-dqth7           0/1     Pending   0          9m31s

kubectl describe pod coredns-6488c6fcc6-p4crr -n kube-system
kubectl describe pod local-path-provisioner-5ff76fc89d-lprrr -n kube-system
kubectl describe pod metrics-server-86cbb8457f-dqth7 -n kube-system
Warning  FailedScheduling  9m4s  default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.

Hoping this will be solved when cilium is installed, but that doesn't work due to Cluster name = ""
cilium install
ℹ️  using Cilium version "v1.11.1"
🔮 Auto-detected IPAM mode: cluster-pool
❌ Cluster name "" is not valid, must match regular expression: ^[a-z0-9]([-a-z0-9]*[a-z0-9])$
↩️ Rolling back installation...
Error: Unable to install Cilium: invalid cluster name

Can I set cluster name somewhere?

### Cilium Version

v1.11.1 (never made it to installed)

### Kernel Version

5.11
Linux corti2623-awse1pi-1d.corticore.net 5.11.0-1020-aws cilium/cilium#21~20.04.2-Ubuntu SMP Fri Oct 1 13:03:59 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.20.15+k3s1
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15+k3s1", GitCommit:"c7a91e1ccdace64eae4a41b9dc15ef8d7aed6d23", GitTreeState:"clean", BuildDate:"2022-01-25T00:24:54Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15+k3s1", GitCommit:"c7a91e1ccdace64eae4a41b9dc15ef8d7aed6d23", GitTreeState:"clean", BuildDate:"2022-01-25T00:24:54Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

cilium never made it to installed

### Relevant log output

```shell
cilium never made it to installed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rolinh** [comment]
> @asloan7 can you open a GH issues in https://github.com/cilium/cilium-cli instead? Thanks

I transfered it ;)

**Comment by asloan7** [comment]
Thanks!

**Comment by itomsawyer** [comment]
+1 , stuck into the same situation.

vagrant 
debain11 
k3s (v1.22.5+k3s1) 
Cilium version "-service-mesh:v1.11.0-beta.1"

**Comment by itomsawyer** [comment]
Found workaround solution:  add options  --cluster-name default  to explicit specify the cluster name.

**Comment by tklauser** [comment]
@asloan7 @itomsawyer What version of cilium-cli are you using (`cilium version`) when you observe this issue? How does the `contexts` section in your kubeconfig (`/etc/rancher/k3s/k3s.yaml`) look like?

**Comment by asloan7** [comment]
@itomsawyer how are you installing k3s?

**Comment by tklauser** [comment]
@asloan7 Does it work if you specify `KUBECONFIG` as instructed in the [quick start guide](https://docs.cilium.io/en/v1.11/gettingstarted/k8s-install-default/), i.e. `KUBECONFIG=/etc/rancher/k3s/k3s.yaml cilium install`?

**Comment by tklauser** [comment]
FWIW, the fact that `KUBECONFIG=/etc/rancher/k3s/k3s.yaml` is needed for `cilium install` to work on k3s is documented in the quick start guide, but not the [k3s-specific guide](https://docs.cilium.io/en/v1.11/gettingstarted/k3s/). I'll send a fix for the latter

**Comment by asloan7** [comment]
Ah yes I missed that, unless cilium-cli can detect it is a k3s install (unreasonable to ask) it wouldn't know where that is. And yes I was reading https://docs.cilium.io/en/v1.11/gettingstarted/k3s/
Also did not need --cluster-name default

**Comment by asloan7** [comment]
@tklauser  Better to export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
So all subsequent cilium commands work, like cilium status --wait

**Comment by tklauser** [comment]
@asloan7 That's a good point, thanks for the suggestion. I'll send a follow-up doc change.

**Comment by asloan7** [comment]
@tklauser there is also a discrepancy between the 2 pages with the flag "disable-network-policy" - do we need it?

(k3s tab) https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='--flannel-backend=none' sh -

https://docs.cilium.io/en/stable/gettingstarted/k3s/#k3s-install
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='--flannel-backend=none --disable-network-policy' sh -

**Comment by tklauser** [comment]
@asloan7 yes, the `--disable-network-policy` flag should appear in both places. This is already fixed in `master` branch (see https://docs.cilium.io/en/latest/gettingstarted/k8s-install-default/) and will be fixed in the v1.10 and v1.11 docs once cilium/cilium#18671 is backported to these branches (presumably some time later this week).

**Comment by tklauser** [comment]
The docs were changed to mention `export KUBECONFIG=/etc/rancher/k3s/k3s.yaml` in the k3s-specific guides, see https://docs.cilium.io/en/latest/gettingstarted/k3s/ and https://docs.cilium.io/en/latest/gettingstarted/k8s-install-default/ (k3s tab). As mentioned above, it might take a while for the doc changes to be backported to the v1.10 and v1.11 docs.

I think this should solve the issue originally reported. In case you still see the problem please comment here or open a new issue.
