### ISSUE TITLE
cilium install fail on k3s ubuntu - Unable to get or create the Cilium CA Secret

### ISSUE THREAD

**Issue by gitsmiles** [cilium/cilium-cli#727]
## Bug report

**General Information**

- Cilium CLI version (run `cilium version`)
- Orchestration system version in use (e.g. `kubectl version`, ...)
- Platform / infrastructure information (e.g. AWS / Azure / GCP, image / kernel versions)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip: `cilium sysdump`

**How to reproduce the issue**

1. instruction 1
   multipass launch  -n cilium
  multipass launch  -n c-node01

2. instruction 2
   following this https://docs.cilium.io/en/latest/gettingstarted/k3s/
   First, with no CNI, node is not ready
ubuntu@cilium:/var/lib/rancher/k3s/server$ sudo k3s kubectl get nodes -n kube-system
NAME       STATUS     ROLES                  AGE   VERSION
c-node01   NotReady   <none>                 79m   v1.22.6+k3s1
cilium     NotReady   control-plane,master   94m   v1.22.6+k3s1

ubuntu@cilium:/var/lib/rancher/k3s/server$ sudo k3s kubectl get pods -n kube-system
NAME                                      READY   STATUS    RESTARTS   AGE
coredns-96cc4f57d-gwwmj                   0/1     Pending   0          94m
helm-install-traefik--1-nv7m8             0/1     Pending   0          94m
helm-install-traefik-crd--1-m96lt         0/1     Pending   0          94m
metrics-server-ff9dbcb6c-fz7db            0/1     Pending   0          94m
local-path-provisioner-84bb864455-zcmxs   0/1     Pending   0          94m

3. instruction 3
ubuntu@cilium:/var/lib/rancher/k3s/server$ echo $KUBECONFIG
/etc/rancher/k3s/k3s.yaml
ubuntu@cilium:/var/lib/rancher/k3s/server$ sudo cilium install --cluster-name default
ℹ️  using Cilium version "v1.11.2"
🔮 Auto-detected IPAM mode: cluster-pool
❌ Unable to get or create the Cilium CA Secret: Get "http://localhost:8080/api/v1/namespaces/kube-system/secrets/cilium-ca": dial tcp [::1]:8080: connect: connection refused
↩️ Rolling back installation...

Error: Unable to install Cilium: Get "http://localhost:8080/api/v1/namespaces/kube-system/secrets/cilium-ca": dial tcp [::1]:8080: connect: connection refused

Cilium Version
ubuntu@cilium:/var/lib/rancher/k3s/server$ sudo cilium version
cilium-cli: v0.10.4 compiled with go1.17.7 on linux/amd64
cilium image (default): v1.11.2
cilium image (stable): v1.11.2
cilium image (running): unknown. Unable to obtain cilium version, no cilium pods found in namespace "kube-system"

ubuntu@cilium:/var/lib/rancher/k3s/server$ uname -a
Linux cilium 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

ubuntu@cilium:/var/lib/rancher/k3s/server$ sudo kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1", GitCommit:"3228d9cb9a4727d48f60de4f1ab472f7c50df904", GitTreeState:"clean", BuildDate:"2022-01-25T01:27:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1", GitCommit:"3228d9cb9a4727d48f60de4f1ab472f7c50df904", GitTreeState:"clean", BuildDate:"2022-01-25T01:27:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

ubuntu@cilium:/var/lib/rancher/k3s/server$ sudo cilium sysdump
🔍 Collecting Kubernetes nodes
failed to create sysdump collector: failed to collect Kubernetes nodes: Get "http://localhost:8080/api/v1/nodes": dial tcp [::1]:8080: connect: connection refused

**Comment by tklauser** [comment]
>     3. instruction 3
>        ubuntu@cilium:/var/lib/rancher/k3s/server$ echo $KUBECONFIG
>        /etc/rancher/k3s/k3s.yaml
>        ubuntu@cilium:/var/lib/rancher/k3s/server$ sudo cilium install --cluster-name default

When using `sudo`, the environment variables (namely `KUBECONFIG`) of the calling won't be preservent . I think you either need to use `sudo -E cilium install` to keep the environment variables or use `cilium install` without `sudo`.

**Comment by gitsmiles** [comment]
> 

Thanks
