### ISSUE TITLE
cilium install --config only takes one key=value

### ISSUE THREAD

**Issue by vosdev** [cilium/cilium-cli#747]
## Bug report

**General Information**

- Cilium CLI version (run `cilium version`) 0.10.4
- Orchestration system version in use (e.g. `kubectl version`, ...) 1.23.4
- Platform / infrastructure information (e.g. AWS / Azure / GCP, image / kernel versions) n/a
- Link to relevant artifacts (policies, deployments scripts, ...) n/a
- Generate and upload a system zip: `cilium sysdump` n/a

I would like to request clarification in the `--help` that `--config` needs to be called for each key=value that you wish to set.

I just set up my cluster with ` --config enable-ipv6=true enable-ipv6-masquerade=false k8s-api-server=https://ebpf-test.example.com:6443` and i was a bit surprised that it didn't take the second+third key=value because the current flag states the plural `strings` not `string`.

Perhaps I should report this as a bug with the --config option instead because it only parses the first string?

Output from cilium install with `--config enable-ipv6=true enable-ipv6-masquerade=false k8s-api-server=https://ebpf-test.example.com:6443`
```
🚀 Creating ConfigMap for Cilium version 1.11.2...
ℹ️ Manual overwrite in ConfigMap: enable-ipv6=true
🚀 Creating Agent DaemonSet...
```
And with a  `--config` for each key-value:
```
🚀 Creating Cluster roles...
🚀 Creating ConfigMap for Cilium version 1.11.2...
ℹ️ Manual overwrite in ConfigMap: enable-ipv6=true
ℹ️ Manual overwrite in ConfigMap: enable-ipv6-masquerade=false
ℹ️ Manual overwrite in ConfigMap: k8s-api-server=https://ebpf-test.example.com:6443
🚀 Creating Agent DaemonSet...
```

**Comment by tklauser** [comment]
Thanks for the report @vosdev.

> I would like to request clarification in the `--help` that `--config` needs to be called for each key=value that you wish to set.
> 
> I just set up my cluster with ` --config enable-ipv6=true enable-ipv6-masquerade=false k8s-api-server=https://ebpf-test.example.com:6443` and i was a bit surprised that it didn't take the second+third key=value because the current flag states the plural `strings` not `string`.
> 
> Perhaps I should report this as a bug with the --config option instead because it only parses the first string?

It should work if you specify the `--config` options separated by comma (but without space), i.e.

```
cilium install --config enable-ipv6=true,enable-ipv6-masquerade=false,k8s-api-server=https://ebpf-test.example.com:6443
```

Otherwise all but the first option will be recognized as positional arguments by the `github.com/spf13/pflag` library (namely the [StringSliceVar](https://pkg.go.dev/github.com/spf13/pflag#StringSliceVar) function) which cilium-cli uses for command line argument parsing.

We should probably extend the usage message for `cilium install --config` to say that the strings need to be comma-separated. Are you interested in sending a PR?
