### ISSUE TITLE
Follow ups for the helm-based installation

### ISSUE THREAD

**Issue by aanm** [cilium/cilium-cli#751]
Follow ups of https://github.com/cilium/cilium-cli/pull/717

- [x] Use the helm values stored in the Cilium's config map under the special key `io.cilium.cilium-cli` to generate hubble manifests
  - [ ] The same needs to be done for the upgrade cli option and any other manifests, clustermesh, hubble-ui that can be enabled prior an installation.
- [x] Deprecate cilium-cli flags that are no longer used once all manifests are helm-generated
  - [x] Done for the `cilium install` command
- [ ] Fix `--version=`

**Comment by giaptx** [comment]
Hi @aanm,
I see #717 is a good PR to make the setup is consistent.

I think some issues because of different of installation. https://github.com/cilium/cilium-cli/issues/427, https://github.com/cilium/cilium-cli/issues/515

Hope you can have a look around.
Thank you very much
