### ISSUE TITLE
Using packages from cilium-cli as a vendored lib to install cilium programmatically inside an environment

### ISSUE THREAD

**Issue by ungureanuvladvictor** [cilium/cilium-cli#776]
## Proposal / RFE
Recently I was experimenting with `kind` inside a golang project to programmatically spin up a k8s cluster. The support for `kind` via `go` is pretty good but taking it to the next was to install `cilium` in the env for which I found that I have 2 options:
- run `helm` and deploy the cilium chart
- run `cilium-cli` and have this install + configure cilium inside my `kind` cluster

Both of the options work well but you need to have the `helm` binary, `helm` chart locally or the `cilium-cli` binary. Did you folks consider exposing the internals of the `cilium-cli` for other consumers to vendor in their code and use? I was chatting with @michi-covalent  about this and would be pretty nifty to have access to https://github.com/cilium/cilium-cli/blob/0af00d450144f2c656394f5d6391657050937825/install/install.go#L293-L305. Right now I cannot vendor this because it's included in the `internal` package which `golang` forbids:
```
could not import github.com/cilium/cilium-cli/internal/k8s (invalid use of internal package github.com/cilium/cilium-cli/internal/k8s)
```

**Comment by michi-covalent** [comment]
@tklauser mentioned there is also https://github.com/cilium/cilium-cli/issues/618 which seems related.

**Comment by ungureanuvladvictor** [comment]
Yep -- that is exactly what I'm looking for. @michi-covalent feel free to close this and consolidate in the other one if you think that is right.

**Comment by michi-covalent** [comment]
i'll take a stab at this
