### ISSUE TITLE
Cilium Daemonset Installation issue on installing Cilium CLI

### ISSUE THREAD

**Issue by Shikhar0411** [cilium/cilium-cli#786]
Installing Cilium CLI using the quick installation method is leading to this issue. Cilium doesnt seem properly installed, but I need the cilium CLI to install it, which itself is not getting installed.
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/65883517/162888288-c6eb829e-e966-44aa-a50c-efb7b744b197.png">

**Comment by tklauser** [comment]
Thanks for the report @Shikhar0411. Which command did you use to install Cilium? What version of the Cilium CLI (`cilium version`) are you using?

**Comment by Shikhar0411** [comment]
https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/ I followed the steps here from installing a Cilium CLI. I already had a running GKE cluster
