### ISSUE TITLE
Installation failure for v1.11.3 on DigitalOcean Error: Unable to install Cilium: serviceaccounts "cilium" already exists

### ISSUE THREAD

**Issue by zaks** [cilium/cilium-cli#815]
## Bug report

**General Information**

- Cilium CLI version (run `cilium version`)

 ➜➜➜ cilium version
cilium-cli: v0.11.2 compiled with go1.18.1 on darwin/amd64
cilium image (default): v1.11.3
cilium image (stable): v1.11.4
cilium image (running): v1.10.4

- Orchestration system version in use (e.g. `kubectl version`, ...)

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:41:58Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-02-16T11:43:55Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}

- Platform / infrastructure information (e.g. AWS / Azure / GCP, image / kernel versions)

DigitalOcean - latest
Debian GNU/Linux 10 (buster)   5.10.0-0.bpo.9-amd64

- Link to relevant artifacts (policies, deployments scripts, ...)

Installation in accordance with Quick installation

**How to reproduce the issue**

Run cilium install

**Comment by odidev** [comment]
I am also getting the same error message, Is there any update on the above issue?

**Comment by zaks** [comment]
Cilium is installed by default on this cloud.
