### ISSUE TITLE
## Proposal / Add a option in  `cilium install`  to strip the sha256 of the docker image for the installation without Internet

### ISSUE THREAD

**Issue by xtay573269555** [cilium/cilium-cli#821]
## Proposal / Add a option in  `cilium install`  to strip the sha256 of the docker image for the installation without Internet

**Is your feature request related to a problem?**

Yes. I tried to install cilium in a k8s without Internet, but failed to start the pod due to wrong images. The default images are the following:
```
Image versions    cilium             quay.io/cilium/cilium:v1.11.3@sha256:cb6aac121e348abd61a692c435a90a6e2ad3f25baa9915346be7b333de8a767f: 3
                  cilium-operator    quay.io/cilium/operator-generic:v1.11.3@sha256:5b81db7a32cb7e2d00bb3cf332277ec2b3be239d9e94a8d979915f4e6648c787: 1
```

As you know that the sha256 will be lost after i download the images from one PC which is able to connect to the Internet and then transfer them to the k8s nodes, and it leads to a failure of cilium installation. (If pull and push the images to another registry, the sha256 will be changed.)

**Describe the solution you'd like**

I tried the command `cilium install --image-tag="v1.11.3"`, while it did not change all the image's tag. This is the result:
```
Image versions    cilium-operator    quay.io/cilium/operator-generic:v1.11.3@sha256:5b81db7a32cb7e2d00bb3cf332277ec2b3be239d9e94a8d979915f4e6648c787: 1
                  cilium             quay.io/cilium/cilium:v1.11.3: 3
```

Hope there is a way to strip the sha256 of images during the cilium installation. Sometimes there are several regulations of security so that some production servers cannot connect to the Internet. Thanks a lot.

**Comment by xiaods** [comment]
no way to implement, because cilium helm params have no options for cilium images
