### ISSUE TITLE
Cli Doesn't work with cilium install in namespace other than kube-system

### ISSUE THREAD

**Issue by c19** [cilium/cilium-cli#853]
## Bug report

**General Information**

- Cilium CLI version (run `cilium version`)
cilium-cli: v0.11.7 compiled with go1.18.2 on darwin/amd64
- Orchestration system version in use (e.g. `kubectl version`, ...)
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-eks-0d102a7", GitCommit:"eb09fc479c1b2bfcc35c47416efb36f1b9052d58", GitTreeState:"clean", BuildDate:"2022-02-17T16:36:28Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
- Platform / infrastructure information (e.g. AWS / Azure / GCP, image / kernel versions)
EKS 1.22
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip: `cilium sysdump`

**How to reproduce the issue**

1. install cilium namespace say `infra`
2. cilium status tells that can't find cilium daemonset.

**Comment by c19** [comment]
my bad, there's -n  option. Don't know why i missed that.lol.

**Comment by tklauser** [comment]
Thanks for the report. Which command did you use to install Cilium? Recent versions of the CLE have the `-n`/`--namepsace` flag which needs to be set on every invocation of the `cilium` command to set the namespace.
