### ISSUE TITLE
install: remove the hidden --base-version flag

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium-cli#886]
the `--base-version` flag was added before we moved to helm-based installation. the purpose of the flag was to identify the cilium version when it couldn't be inferred from image tags (e.g. CI images with commit SHA as image tags). 

with helm-based installation, we can always rely on the `--version` flag to identify which helm chart version is being used for installation, so the `--base-version` is no longer necessary.

**Comment by tklauser** [comment]
Fixed by #890 and #891.
