### ISSUE TITLE
Cilium connectivity test fails: unable to retrieve helm values secret kube-system/cilium-cli-helm-values

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium-cli#927]
Failed during testing of new Helm charts for latest Cilium releases:
https://github.com/cilium/charts/runs/6908352807?check_suite_focus=true

Workflow:
https://github.com/cilium/charts/blob/master/.github/workflows/conformance-gke.yaml

Looks like this uses helm to install Cilium, then cilium connectivity test to validate.

```
...
connectivity test failed: unable to retrieve helm values secret kube-system/cilium-cli-helm-values: secrets "cilium-cli-helm-values" not found
```

This previously passed a month ago. Not sure if the latest release of cilium-cli as of today is broken or if the workflow above needs to be updated in some way.

**Comment by aanm** [comment]
It looks like this is a regressions in 0.11.8? Nicolas mentioned that this was failing in cilium/cilium as well

**Comment by michi-covalent** [comment]
ah cilium/charts doesn't use `cilium install` huh. that's a trouble.
