### ISSUE TITLE
ServiceAccount hubble-relay left in-place after `cilium uninstall`

### ISSUE THREAD

**Issue by tklauser** [cilium/cilium-cli#97]
Steps to reproduce:

```
$ cilium install --cluster-name $CLUSTER_NAME
$ cilium hubble enable
$ cilium uninstall
```

After not using the cluster for a while, I attempted to re-install `cilium` using `helm`:

```
$ helm repo add cilium https://helm.cilium.io
$ helm repo update
$ helm install -n kube-system --set hubble.relay.enabled=true cilium cilium/cilium
```

This lead to the following error:

```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "hubble-relay" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "cilium-enterprise"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"
```

The `ServiceAccount` is indeed still there:

```
$ kubectl -n kube-system get serviceaccount hubble-relay
NAME                 SECRETS   AGE
hubble-relay         1         23m
```

Naturally, I would have expected that `ServiceAccount` to be uninstalled as well by `cilium uninstall`. Note that I can still get rid of it using `cilium hubble disable` before or after `cilium uninstall`. It might be more user-friendly though to remove as part of `cilium uninstall` as well, given all other `hubble-relay` objects are uninstalled.

**Comment by kaworu** [comment]
> helm install -n kube-system cilium cilium/cilium

This is missing `--set hubble.relay.enabled=true` right?
